### ISSUE TITLE
proxy.api.auth and proxy.auth 

### ISSUE THREAD

**Issue by Juancollado2003** [master-coder-ll/v2ray-web-manager#10]
Hi, there are not instructions on how to change or edit this config, any help please?

**Comment by master-coder-ll** [comment]
Generate and use the same key[0-9,a-z,A-Z..]

**Comment by Juancollado2003** [comment]
> Generate and use the same key[0-9,a-z,A-Z..]

Can you please make an example on how should looks like the format of file?

**Comment by goodjimli** [comment]
Any normal string, any length. But only you know That
e.g:Ssdfccsaq17774c#

**Comment by master-coder-ll** [comment]
> > Generate and use the same key[0-9,a-z,A-Z..]
> 
> Can you please make an example on how should looks like the format of file?

e.g:keysdx_ws15

**Comment by Juancollado2003** [comment]
Do you mean

proxy.api.auth:123456
proxy.auth:123456

?

> > > Generate and use the same key[0-9,a-z,A-Z..]
> > 
> > 
> > Can you please make an example on how should looks like the format of file?
> 
> e.g:keysdx_ws15

**Comment by master-coder-ll** [comment]
> Do you mean
> 
> proxy.api.auth:123456
> proxy.auth:123456
> 
> ?
> 
> > > > Generate and use the same key[0-9,a-z,A-Z..]
> > > 
> > > 
> > > Can you please make an example on how should looks like the format of file?
> > 
> > 
> > e.g:keysdx_ws15

Yes
