### ISSUE TITLE
邮箱问题

### ISSUE THREAD

**Issue by VeryAdd** [master-coder-ll/v2ray-web-manager#102]
有谁能告知一下 如何设置邮箱发送吗？
服务器上是否需要开启特地端口？
我使用QQ邮箱的话 是否可以 还是说要使用域名邮箱之类的。
或者，如何关闭注册的邮箱部分 也可以

**Comment by VeryAdd** [comment]
如果您的邮件客户端不在上述列出的范围内，您可以尝试如下通用配置：
接收邮件服务器：imap.qq.com
发送邮件服务器：smtp.qq.com
账户名：您的QQ邮箱账户名（如果您是VIP邮箱，账户名需要填写完整的邮件地址）
密码：您的QQ邮箱密码
电子邮件地址：您的QQ邮箱的完整邮件地址
 
 
如何设置IMAP服务的SSL加密方式？
使用SSL的通用配置如下：
接收邮件服务器：imap.qq.com，使用SSL，端口号993
发送邮件服务器：smtp.qq.com，使用SSL，端口号465或587
账户名：您的QQ邮箱账户名（如果您是VIP帐号或Foxmail帐号，账户名需要填写完整的邮件地址）
密码：您的QQ邮箱密码
电子邮件地址：您的QQ邮箱的完整邮件地址

**Comment by master-coder-ll** [comment]
支持 smtp发邮件，不需要特定端口。什么是smtp，怎么开通smtp 自己百度
