### ISSUE TITLE
请教一下作者，如何开启用户等级制度？

### ISSUE THREAD

**Issue by twinklstar** [master-coder-ll/v2ray-web-manager#106]
## 你的问题是什么？
想开放用户等级制度，但是找了一大圈也没找到，只看到issues里面您提到了用户等级制度，我在web面板也看到了用户等级这个词眼，但是找不到在哪里设置。

**Comment by master-coder-ll** [comment]
编辑用户你可以看见有个等级

编辑服务器你可以看见有个等级

**Comment by twinklstar** [comment]
> 编辑用户你可以看见有个等级
> 
> 编辑服务器你可以看见有个等级

看到了谢谢作者！
