### ISSUE TITLE
Proxy rejects connection 

### ISSUE THREAD

**Issue by Juancollado2003** [master-coder-ll/v2ray-web-manager#11]
2020-01-28 20:25:45.738  INFO 2886 --- [nioEventLoopGroup-3-2] c.jhl.proxy.HexDumpProxyFrontendHandler  : 关闭当前连接数后->account:eh2mn8z,：0
2020-01-28 20:25:45.818  INFO 2886 --- [nioEventLoopGroup-3-1] c.jhl.proxy.HexDumpProxyFrontendHandler  : 当前连接数account:eh2mn8z,1
2020-01-28 20:25:45.818 ERROR 2886 --- [nioEventLoopGroup-3-1] c.jhl.proxy.HexDumpProxyFrontendHandler  : 来源host错误 from :1xx.1xx.1xx.1xx:8008 ,to:1xx.1xx.1xx.1xx
2020-01-28 20:25:45.819  INFO 2886 --- [nioEventLoopGroup-3-1] c.jhl.proxy.HexDumpProxyFrontendHandler  : 关闭当前连接数后->account:eh2mn8z,：0

**Comment by master-coder-ll** [comment]
The http host isn't equal.

why do you use 8008 port？

**Comment by master-coder-ll** [comment]
I recommend  using nignx to forward ws traffic

**Comment by Juancollado2003** [comment]
> The http host isn't equal.
> 
> why do you use 8008 port？

"The http host isn't equal" how can I make it equal?
I use port 8008 on nginx just to test, should I use 80 on nginx?

**Comment by goodjimli** [comment]
80 or 443 
Make sure your "服务器配置-访问域名" equal

**Comment by goodjimli** [comment]
Other ports need to modify some codes

**Comment by master-coder-ll** [comment]
> > The http host isn't equal.
> > why do you use 8008 port？
> 
> "The http host isn't equal" how can I make it equal?
> I use port 8008 on nginx just to test, should I use 80 on nginx?

Make sure that 'admin端 服务器-访问域名' equal to the host in the http head.

Other ports need to modify the code

**Comment by master-coder-ll** [comment]
> > > The http host isn't equal.
> > > why do you use 8008 port？
> > 
> > 
> > "The http host isn't equal" how can I make it equal?
> > I use port 8008 on nginx just to test, should I use 80 on nginx?
> 
> Make sure that 'admin端 服务器-访问域名' equal to the host in the http head.
> 
> Other ports need to modify the code.

The host in http head should not have port.

**Comment by Juancollado2003** [comment]
> > > > The http host isn't equal.
> > > > why do you use 8008 port？
> > > 
> > > 
> > > "The http host isn't equal" how can I make it equal?
> > > I use port 8008 on nginx just to test, should I use 80 on nginx?
> > 
> > 
> > Make sure that 'admin端 服务器-访问域名' equal to the host in the http head.
> > Other ports need to modify the code.
> 
> The host in http head should not have port.

Now is working, thanks
