### ISSUE TITLE
邀请码功能的改进建议

### ISSUE THREAD

**Issue by MuZhou233** [master-coder-ll/v2ray-web-manager#112]
## 现状
1. 同一时间只能有一个未使用的邀请码
1. 已使用的邀请码无法查看被哪个账号用于注册
1. 已生成的邀请码无法删除
1. 已生成的邀请码永久有效

## 建议
1. 允许同时有多个未使用的邀请码
1. 显示已使用的邀请码注册的账号
1. 允许删除邀请码
1. 允许自定义邀请码有效期

**Comment by master-coder-ll** [comment]
有道理

**Comment by master-coder-ll** [comment]
已经实现
