### ISSUE TITLE
個人自訂化及語言建議

### ISSUE THREAD

**Issue by lawrence1751** [master-coder-ll/v2ray-web-manager#113]
## 你的问题是什么？
1. 希望可以新增更改右上角大頭貼的選項
2. 希望可以提供類似pe文檔讓其他人可以翻譯網站介面

例如: 我想貢獻翻譯繁體中文、英文版本，目前已在別的面板貢獻過繁體中文版本，期待開發者釋出文檔，謝謝！

**Comment by master-coder-ll** [comment]
前期，没做国际化的埋点。所以现在只能在具体代码中修改。抱歉

**Comment by lawrence1751** [comment]
沒關係，謝謝！
