### ISSUE TITLE
Java小白提问下，如何本地跑起你的后台api

### ISSUE THREAD

**Issue by sumingjun1994** [master-coder-ll/v2ray-web-manager#114]
## 你的问题是什么？
如何本地跑起你的后台api
有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

**Comment by master-coder-ll** [comment]
看文档

**Comment by sumingjun1994** [comment]
> 看文档

文档好像没有地方说明？

**Comment by sumingjun1994** [comment]
> 看文档

我已经用IDE启动了服务，但是前台运行连接不上服务，是不是转发代理还需要配置下？

**Comment by master-coder-ll** [comment]
本地？ 本地有点难。涉及很多东西。
