### ISSUE TITLE
麻烦问一下添加多个账号会正常吗？

### ISSUE THREAD

**Issue by bbhxwl** [master-coder-ll/v2ray-web-manager#115]
麻烦问一下添加多个账号会正常吗？我测试了好几个人的后端，uuid好像达到200个以上，程序就无法正常使用，不知道为什么。请问这个后端添加账号，删除，会让所有人都掉线吗？重启v2ray服务？

**Comment by master-coder-ll** [comment]
什么玩意？ 有图吗？ 有日志吗

**Comment by master-coder-ll** [comment]
机器人？ 每个项目都这么问？
