### ISSUE TITLE
关于cdn

### ISSUE THREAD

**Issue by ghost** [master-coder-ll/v2ray-web-manager#116]
admin端用了域名，怕被和谐，还套了cdn，
套了后，就无法使用翻墙了，
proxy端配置文件的address我写的是admin端的域名。

**Comment by newsouther** [comment]
admin和proxy在两台电脑

**Comment by master-coder-ll** [comment]
我在用的cloudflare cdn 一切正常

**Comment by lawrence1751** [comment]
**proxy.yaml檔案裡的admin端的位址不能為掛CDN的域名，因為admin端預設的溝通端口是9091**

在proxy端的proxy.yaml檔案內要將
manager:
  address: http://**admin端的IP**或是**可解析的域名**:9091

例:
admin 端: cdn.domain.com(已掛CDN) 原VPS的IP位址為a.b.c.d

那麼你在proxy.yaml裡面就必須填寫為
manager:
  address: http://a.b.c.d:9091

如果你填寫為http://cdn.domain.com:9091 則無法連結，因為CDN通常不會開放9091傳輸埠
又或是你想把管理端口改成CDN有開放的傳輸埠也可以

**Comment by newsouther** [comment]
> **proxy.yaml檔案裡的admin端的位址不能為掛CDN的域名，因為admin端預設的溝通傳輸埠是9091**
> 
> 在proxy端的proxy.yaml檔案內要為
> 
> ```
> manager:
>   address: http://"admin端的IP"或"可解析的域名":9091
> ```
> 
> 例:
> admin 端: cdn.domain.com(已掛CDN) 原VPS的IP位址為a.b.c.d
> 
> 那麼你在proxy.yaml裡面就必須填寫為
> 
> ```
> manager:
>   address: http://a.b.c.d:9091
> ```
> 
> 如果你填寫為http://cdn.domain.com:9091 則無法連結，因為CDN通常不會開放9091傳輸埠
> 又或是你想把9091改成CDN有開放的傳輸埠也可以

谢谢！已经解决了。我一开始也觉得是域名的问题，但是没有足够的理由让我去换成ip。

**Comment by lawrence1751** [comment]
不會，如果不想填IP在檔案裡面了話可以自己再多做個DNS解析(a.domain.com)到你的VPS就好，9091傳輸埠（非CDN供轉發的傳輸埠）的條件下只要不要套CDN即可

例:
```
manager:
  address: http://a.domain.com:9091
 #注意: a.domain.com不掛CDN
```
