### ISSUE TITLE
流量整形的问题

### ISSUE THREAD

**Issue by vousembrasser** [master-coder-ll/v2ray-web-manager#117]
## 你的问题是什么？
开启流量整形后 用户下载被限速 当下载被用户手动停止之后, 服务端还在继续发送数据
大量数据会导致积压会导致oom

## 期望结果？
用户停止下载后 缓存清空

**Comment by master-coder-ll** [comment]
日志提供下

**Comment by vousembrasser** [comment]
最新版的,服务在自己笔记本上跑的,手动限制速度下载,之后下载一段时间然后暂停下载,在下载提示速度的软件上发现,还有下载速度

**Comment by master-coder-ll** [comment]
情况：4月份之后，都加入了`高低水位线`进行控制，在流量控制导致堆积的时候，会到达高水位线，暂停接收数据。并且通过TCP协议的`滑动窗口`扩散出去。

在说一下我的使用情况，在下载和电影环境、长时间均没有发现oom情况

**Comment by vousembrasser** [comment]
会不会存在这种情况 大量用户下载内存吃不消呢

**Comment by master-coder-ll** [comment]
> 会不会存在这种情况 大量用户下载内存吃不消呢

你多大的体量

**Comment by vousembrasser** [comment]
我一个人用😂
