### ISSUE TITLE
v2ray ws request host

### ISSUE THREAD

**Issue by Juancollado2003** [master-coder-ll/v2ray-web-manager#12]
Sorry for all this questions, on v2ray client I want to use a request host, like obfs, but it breaks connection on this server, any help please?

2020/01/31 02:03:35 [error] 27351#0: *2 upstream prematurely closed connection while reading response header from upstream, client: MYCLIENTIP, server: MYSERVERHOST, request: "GET /ws/n7c7pxa/ HTTP/1.1", upstream: "http://127.0.0.1:8081/ws/n7c7pxa/", host: "www.google.com"

**Comment by master-coder-ll** [comment]
It’s need to motifs core


> Sorry for all this questions, on v2ray client I want to use a request host, like obfs, but it breaks connection on this server, any help please?
> 
> 2020/01/31 02:03:35 [error] 27351#0: *2 upstream prematurely closed connection while reading response header from upstream, client: MYCLIENTIP, server: MYSERVERHOST, request: "GET /ws/n7c7pxa/ HTTP/1.1", upstream: "http://127.0.0.1:8081/ws/n7c7pxa/", host: "www.google.com"

Modifying host to googe.com is useless.

If you want this, you need to modify the code.

**Comment by Juancollado2003** [comment]
> > Sorry for all this questions, on v2ray client I want to use a request host, like obfs, but it breaks connection on this server, any help please?
> > 2020/01/31 02:03:35 [error] 27351#0: *2 upstream prematurely closed connection while reading response header from upstream, client: MYCLIENTIP, server: MYSERVERHOST, request: "GET /ws/n7c7pxa/ HTTP/1.1", upstream: "http://127.0.0.1:8081/ws/n7c7pxa/", host: "www.google.com"
> 
> Modifying host to googe.com is useless.
> 
> If you want this, you need to modify the code.

The host in ws is used to bypass CaptivePortal, is very useful on client side, do you work the source with eclipse?

**Comment by master-coder-ll** [comment]
The project development environment is **maven**, eclipse is just a development tool, you need to install maven, java environment.

But host is used in the current project to prevent users from accessing all servers without authorization. So if you remove this check, users can ignore the configuration to access all servers.

If you must do this, you can remove `HexDumpProxyFrontendHandler.java
Lines 129 to 134`, and remove the relevant host configuration in the nginx configuration file `proxy_set_header Host $ http_host;`

At the same time, you have to package the java project. Execute `mvn clean install -Dmaven.test.skip = true ` in the project root directory

I hope you have a certain java foundation and good luck.

**Comment by Juancollado2003** [comment]
Many thanks for your instructions, many projects are being migrated to python, not just for resources management improvements but also because it's easy to modify
