### ISSUE TITLE
配置集群出错了，求助

### ISSUE THREAD

**Issue by GeekerFeng** [master-coder-ll/v2ray-web-manager#120]
## 你的问题是什么？

在配置第二台服务器的时候报错了 ，admin 在另外一台服务器上，另外一台服务器上的proxy是可以正常运行， 在配置第二台服务器的时候，使用配置集群的教程，出现了错误

## 相关日志

***** 表示隐藏了域名 域名输入是正确的

addProxyAccount error:UNAVAILABLE: io exception,{"version":1591604908138,"accountId":5,"host":"****","accountNo":"5j1xo0a","id":"e32d2ad4-93a6-4c4d-89fe-e2d6169613c4","alterId":64,"level":0,"email":"admin@admin.com","inBoundTag":"6001","upTrafficLimit":5120000,"downTrafficLimit":5120000,"maxConnection":128,"v2rayHost":"*","v2rayPort":6001,"v2rayManagerPort":62789,"proxyIp":"*"}

**Comment by hkurj** [comment]
折腾了一天解决了

**Comment by master-coder-ll** [comment]
> 折腾了一天解决了

提示什么？错误信息？

**Comment by master-coder-ll** [comment]
看似，无法通信到第二台服务器

**Comment by hkurj** [comment]
网页上的配置我都配置成  新建的服务的的域名了  有2个v2ray和proxy的地址应该写成127.0.0.1
