### ISSUE TITLE
docker下的run.sh启动jar的内存大小设置问题

### ISSUE THREAD

**Issue by liuchengts** [master-coder-ll/v2ray-web-manager#121]
docker下的run.sh脚本启动admin.jar的-Xmx参数设置过小

导致启动过程中直接内存不够，springboot启动失败

![image](https://user-images.githubusercontent.com/28919312/84104383-1da5e500-aa48-11ea-82dc-f20c82c4fc72.png)

解决方式：
将run.sh 中的第二行
nohup java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=100M -XX:MaxMetaspaceSize=180m /opt/jar/admin.jar --spring.config.location=/opt/conf/admin.yaml >> /opt/admin.log &
中 -Xmx40m  改为 -Xmx100m 即可 （可以去尝试50m、80m等）

**Comment by newsouther** [comment]
俺使用原来的木有问题

**Comment by liuchengts** [comment]
> 使用原来的木有问题

嗯 可能这个问题与docker版本相关

**Comment by greatbody** [comment]
> > 使用原来的木有问题
> 
> 嗯 可能这个问题与docker版本相关

欢迎提PR，docker的支持就是我的PR加进去的。
