### ISSUE TITLE
Request failed with status code 502

### ISSUE THREAD

**Issue by djx2726889** [master-coder-ll/v2ray-web-manager#122]
进行登录时登录界面显示Request failed with status code 502

**Comment by xinxinyihao** [comment]
我的也一直都是这个问题，不知道怎么解决了。ps查看，admin进程在，查看日志，admin.log.ERROR，这个文件一直都是空的。求支援

**Comment by yfqh11** [comment]
我也是这样，一直登录不上

**Comment by crazyit** [comment]
我目前也是遇到这个问题，一直登录不了

**Comment by crazyit** [comment]
我解决这个问题了，我看了一下nginx的error.log,发现是权限问题。2020/08/03 05:50:27 [crit] 2187#0: *15 connect() to 127.0.0.1:9091 failed (13: Permission denied) while connecting 
to upstream，如果你的报错日志跟这个一样。尝试这个办法。https://stackoverflow.com/questions/23948527/13-permission-denied-while-connecting-to-upstreamnginx

**Comment by 900561y** [comment]
i can not login too, same problem with/on ubuntu 20.x
admin.yaml file edited with the admin login details, but it isnt working
sometimes getting account/password error - sometimes getting 502 error
any easy&fast solutions for this?

**Comment by 900561y** [comment]
and now it's working.
i followed this: https://github.com/master-coder-ll/v2ray-web-manager/issues/62
and added rights to those stop and start and for the jar

**Comment by matthuo333** [comment]
> 我解决这个问题了，我看了一下nginx的error.log,发现是权限问题。2020/08/03 05:50:27 [crit] 2187#0: *15 connect() to 127.0.0.1:9091 failed (13: Permission denied) while connecting
> to upstream，如果你的报错日志跟这个一样。尝试这个办法。https://stackoverflow.com/questions/23948527/13-permission-denied-while-connecting-to-upstreamnginx

按照这个方法不错。可是有两个奇怪的地方：

1. VPS 从suspend 状态恢复后，出现这个问题；
2. 按照这个方法后，发现日志都不工作了。需要重新在启动各个服务？
