### ISSUE TITLE
建议：添加卡密功能

### ISSUE THREAD

**Issue by ghost** [master-coder-ll/v2ray-web-manager#123]
这个面板缺少支付相关的功能，当然，我也不推荐对接支付。
推荐生成卡密功能，使用卡密可以添加对应的有效期和流量。（如果可以：更改用户等级）

可以不？没空的话我可以pr service层

**Comment by newsouther** [comment]
> 欢迎pr，这几个月很忙，所以只能是你独立完成

我想问一下:我想把v2ray docker版和这个项目的docker一起使用，也就是说，宿主机只有v2的配置文件，v2运行在docker上面。这样子的话，这个项目还可以正常控制v2吗？或者说我需要注意点什么？https://toutyrater.github.io/app/docker-deploy-v2ray.html这个是v2官方docker版
