### ISSUE TITLE
在中转机(nat)建立v2r 和proxy怀疑nginx默认配置有问题

### ISSUE THREAD

**Issue by matthuo333** [master-coder-ll/v2ray-web-manager#126]
nginx可以接收到，但是proxy就貌似不行。下面是nginx配置文件，请大神帮忙看看。

https://paste.ubuntu.com/p/bBzkYQvmKB/

https://paste.ubuntu.com/p/pGb75xtPw4/

**Comment by newsouther** [comment]
是我理解有问题吗？在nat搭建v2和proxy。。。人才

**Comment by matthuo333** [comment]
> 是我理解有问题吗？在nat搭建v2和proxy。。。人才

NAT机做中转，上面通过部署一样的proxy和v2r, 达到统一管理的目的。
