### ISSUE TITLE
连接数 Connections

### ISSUE THREAD

**Issue by Juancollado2003** [master-coder-ll/v2ray-web-manager#13]
Connections can't be set below 10, it stop connection on a single device, what's this for anyway?

**Comment by master-coder-ll** [comment]
When the v2ray client processes each request, it will open a TCP socket connection. For example: a web page may open 30 to 40 connections without Mux.

If you don't have very low latency requirements, open Mux for v2ray client. But some clients have some bugs, especially Android . Mux is invalid after it is enabled.

**Comment by Juancollado2003** [comment]
Now I get it
