### ISSUE TITLE
能否出一个apache2下的配置教程

### ISSUE THREAD

**Issue by Narutojoy** [master-coder-ll/v2ray-web-manager#131]
希望大神出一个apache2下的配置教程，谢谢！

**Comment by Narutojoy** [comment]
apache2配置下出现"Request failed with status code 404"，查看admin错误日志直接卡住，没法查看，我的apache配置如下：
--------------------------分割线--------------------------------
<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
		ServerAdmin webmaster@localhost
		ServerName "我的域名"
		DocumentRoot /opt/jar/web

		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined

		SSLEngine on
		SSLCertificateFile	/etc/apache2/ssl/"主证书"
		SSLCertificateKeyFile /etc/apache2/ssl/"密钥"
		SSLCertificateChainFile /etc/apache2/ssl/"中间证书"

<LocationMatch "/api">
        ProxyPass ws://127.0.0.1:9091/ upgrade=WebSocket
</LocationMatch>

<LocationMatch "/ws/">
        ProxyPass ws://127.0.0.1:8081 upgrade=WebSocket
        ProxyAddHeaders Off
        ProxyPreserveHost On
        RequestHeader set Host %{HTTP_HOST}s
        RequestHeader set X-Real-IP $remote_addr
        RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s
</LocationMatch>

	</VirtualHost>
</IfModule>
--------------------------分割线--------------------------------
麻烦大佬看下我哪里出问题了

**Comment by master-coder-ll** [comment]
apache2 没用过

**Comment by Narutojoy** [comment]
好吧，谢谢大佬了～
