### ISSUE TITLE
请教下，项目的源代码是完整的吗

### ISSUE THREAD

**Issue by hyxxsfwy** [master-coder-ll/v2ray-web-manager#133]
### 你的问题是什么？

Git 上的源代码是完整的吗

### 出现问题的情况是怎么样的？
git clone 下来的代码，用 IDE 打开，会发现一堆报错，各种方法未找到……

### 期望结果？
clone 下来的代码可以顺利通过编译

**Comment by master-coder-ll** [comment]
完整
