### ISSUE TITLE
配置好了，但是登录的时候却显示 Request failed with status code 502

### ISSUE THREAD

**Issue by yfqh11** [master-coder-ll/v2ray-web-manager#134]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

**Comment by lawrence1751** [comment]
怎麼設定都沒有說，也不知道你是admin跟proxy都掛同一個VPS，也沒有log紀錄
要就資料提供詳細一點才有人願意幫你

**Comment by master-coder-ll** [comment]
大概是 Java admin 服务没有起来

**Comment by yfqh11** [comment]
那怎么解决呢？

在 2020年7月13日星期一，master-coder-ll <notifications@github.com> 写道：

**Comment by yfqh11** [comment]
我试着搭建了三次都是这样的情况，然后看错误日志，里面是空的，什么都没有

在 2020年7月13日星期一，master-coder-ll <notifications@github.com> 写道：
