### ISSUE TITLE
部署完成后，登录初次账号和密码，已经返回network error

### ISSUE THREAD

**Issue by crazyit** [master-coder-ll/v2ray-web-manager#141]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs
![Snipaste_2020-08-01_11-24-35](https://user-images.githubusercontent.com/6240481/89093095-d4d83000-d3e9-11ea-8e19-d0ba8513c402.png)

相关输出

**Comment by crazyit** [comment]
自己排除解决了，是Nginx未启动造成的

**Comment by alun1** [comment]
我也遇到了，但是我是启动了Nginx的，但是我改过nginx的默认端口，也改了配置文件的
