### ISSUE TITLE
请问账号等级的意思是什么

### ISSUE THREAD

**Issue by dyqnaruto** [master-coder-ll/v2ray-web-manager#147]
## 你的问题是什么？
账号等级的意思是什么

有问题先搜索Issues
已经查过了，只在changelog中提到，但未知作用
## 出现问题的情况是怎么样的？
不清楚该设置作用

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
希望有一个简要说明，谢谢

**Comment by master-coder-ll** [comment]
控制不同等级的用户，使用不同等级的服务器。

**Comment by dyqnaruto** [comment]
好了，谢谢
