### ISSUE TITLE
尝试把同一个用户对应不同服务器的wsPath修改为相同的字符，尝试失败，还望大佬指点一二

### ISSUE THREAD

**Issue by yockrain** [master-coder-ll/v2ray-web-manager#149]
## 你的问题是什么？

起因：看到一篇关于PASSWALL负载均衡的文章，可以把多个v2ray节点配置为一组可负载均衡的节点。但是PASSWALL要求这一组节点的参数必须是相同（如节点类型、传输协议、端口、加密方式、用户ID、传输方式和wsPath【wsPath是一直困扰我的点】）。我已经搭建了多个服务器（1admin+3proxy）（过程还算顺利，感谢大佬），且每个节点都能正常使用。同一个用户对应不同服务器，大多数参数都是相同的，只有“wsPath”是不同的。导致PASSWALL的负载均衡功能无法正常运行。

## 出现问题的情况是怎么样的？

我做了如下尝试，均告失败：
1. 在PASSWALL里删除每个节点的wsPath信息，测试后发现单个节点都不能正常打开网页了，负载均衡就更谈不上了
2. 修改admin服务器里v2ray的配置文件config.json，把ws修改为tcp（看某视频里的演示的节点都是tcp加密，在config.json里对应的是network的值），测试发现单个节点的v2ray账号同样也不能打开网页了
3. 在admin控制台，添加服务器的时候，尝试手动输入“ws路径”，替代原有的字符“/ws/%s/”，虽然这样会使每个节点的wsPath值相同，但是这样生成的v2ray节点无法使用，网页无法打开

## 相关日志 java服务日志位于/opt/jar/logs

暂时不知道该贴哪部分日志出来

## 期望结果？

请大佬做个判断，PASSWALL的负载均衡是否可以跟v2ray-web-manager配合使用。如果能，还请给个思路。如果不能，我也就断了这个期许了，谢谢~

**Comment by master-coder-ll** [comment]
暂时没有对PASSWALL 负载均衡模式进行适配

**Comment by yockrain** [comment]
好的，谢谢~
