### ISSUE TITLE
java 运行失败  急~~ 请大神协助

### ISSUE THREAD

**Issue by matthuo333** [master-coder-ll/v2ray-web-manager#150]
## 你的问题是什么？

java proxy 起不来，请协助跟进

## 出现问题的情况是怎么样的？

当执行  nohup java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &

没有启动成功，进程中没有 java

系统： ubuntu18.04    oracle cloud  剩余内存  137 MB

**Comment by master-coder-ll** [comment]
jar 存在不 /opt/jar/v2ray-proxy.jar ？

换台内存大点的机器

**Comment by matthuo333** [comment]
> jar 存在不 /opt/jar/v2ray-proxy.jar ？
> 
> 
> 
> 换台内存大点的机器

应该和内存没关系，因为比它小的机器就没问题。

proxy jar包也有

是不是和改了v2ray 配置文件位置有关？

**Comment by matthuo333** [comment]
MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m 
这两个参数有关系么？调小点？

**Comment by master-coder-ll** [comment]
> MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m
> 这两个参数有关系么？调小点？

没关系的

**Comment by matthuo333** [comment]
最后经重启机器后，停掉所有应用，是可以将proxy 启动。但是再启动nginx 就proxy就自动停了。
看来和内存有关。
不过还有台机器剩余74M，运行没问题。但看SWAP利用不少。

如果内存不够，是不是可以通过增大swap来解决呢？  求大神提示怎么增加swap呢

**Comment by matthuo333** [comment]
原来proxy.yaml中多了几个空格 所致
