### ISSUE TITLE
现在ibm cloud很火，建议大神支持非root权限下的安装

### ISSUE THREAD

**Issue by matthuo333** [master-coder-ll/v2ray-web-manager#151]
## 你的问题是什么？

建议支持非root权限下的全量安装

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

**Comment by master-coder-ll** [comment]
可以通过 sudo 命令来提权

**Comment by matthuo333** [comment]
> 可以通过 sudo 命令来提权

如果可以就请大神了。
这个系统是ibm裁剪过的，sudo提示不存在。
