### ISSUE TITLE
搭建成功但是添加的本机V2ray无法上油管

### ISSUE THREAD

**Issue by siemenstutorials** [master-coder-ll/v2ray-web-manager#152]
## 你的问题是什么？
搭建成功但是添加的本机V2ray无法上油管
有问题先搜索Issues

## 出现问题的情况是怎么样的？
所有都正常就是无法正常扶墙
重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
添加节点后能正确扶墙

**Comment by master-coder-ll** [comment]
需要更多信息
