### ISSUE TITLE
证书续签失败

### ISSUE THREAD

**Issue by gogokkj** [master-coder-ll/v2ray-web-manager#153]
##请问什么问题？ 
自动续签失效，手动强制更新失败，小白查找许多资料尝试无果，已尝试更新acme

有问题先搜索Issues---issues没找到相关问题

## 出现问题的情况是怎么样的？
无法续签，证书失效。
[root@izj6c7cxmmtvxrfzp19gsrz ~]# acme.sh --cron -f
[Sun Sep 13 21:06:11 CST 2020] ===Starting cron===
[Sun Sep 13 21:06:11 CST 2020] Renew: 'www.example.xyz'
[Sun Sep 13 21:06:12 CST 2020] Single domain='www.example.xyz'
[Sun Sep 13 21:06:12 CST 2020] Getting domain auth token for each domain
[Sun Sep 13 21:06:15 CST 2020] Getting webroot for domain='www.example.xyz'
[Sun Sep 13 21:06:15 CST 2020] Verifying: www.example.xyz
[Sun Sep 13 21:06:19 CST 2020] www.example.xyz:Verify error:Fetching https:///www.example.xyz/.well-known/acme-challenge/l28o2X2A5S9AB4blcrCk6vcyrg4Cf_U-ekIYYrUDisc: Invalid empty hostname in redirect target
[Sun Sep 13 21:06:19 CST 2020] Please add '--debug' or '--log' to check more details.
[Sun Sep 13 21:06:19 CST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sun Sep 13 21:06:20 CST 2020] Error renew www.example.xyz.
[Sun Sep 13 21:06:20 CST 2020] ===End cron===
[root@izj6c7cxmmtvxrfzp19gsrz ~]#

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
续签证书成功

**Comment by gogokkj** [comment]
大佬需要我提供什么 我尽力去提供

**Comment by master-coder-ll** [comment]
https://community.letsencrypt.org/t/cant-renew-certificate/91416/2

**Comment by gogokkj** [comment]
感谢大佬！！！ 小弟分享一下解决方法
更改/etc/nginx/conf.d/v2ray-manager.conf文件
末尾这段
server {
    listen 80;
    server_name XXXX.com _www.XXXX.com_;
    _rewrite ^(.*) https://$host$1 permanent;_
    return 301 https:///$http_host$request_uri;
斜字为新添加  保存后重启nginx 再续签acme.sh --cron -f 即可
