### ISSUE TITLE
脚本失效(旧版本代码和新版本的v2ray 不兼容)

### ISSUE THREAD

**Issue by CaoLeiKe** [master-coder-ll/v2ray-web-manager#155]
## 你的问题是什么？
ERROR: This script has been DISCARDED, please switch to fhs-install-v2ray project.
HOW TO USE: https://github.com/v2fly/fhs-install-v2ray
TO MIGRATE: https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this

## 出现问题的情况是怎么样的？
bash <(curl -L -s https://install.direct/go.sh)

## 相关日志 java服务日志位于/opt/jar/logs

ERROR: This script has been DISCARDED, please switch to fhs-install-v2ray project.
HOW TO USE: https://github.com/v2fly/fhs-install-v2ray
TO MIGRATE: https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this

## 期望结果？
老板，这个旧版本和新版本的v2ray 不兼容了

**Comment by master-coder-ll** [comment]
已经更新
