### ISSUE TITLE
成功搭建，用户和服务器配置也正常，可以连同但是不走流量。

### ISSUE THREAD

**Issue by seekky** [master-coder-ll/v2ray-web-manager#161]
## 成功搭建，用户和服务器配置也正常，可以连同但是不走流量。

请大神帮助～
-------------------------

- 能ping得通，shadowrocket也能挂得上，但是任何流量走不通。
- 搭建全程唯独在安装v2ray的环节上有包过以下警示代码：

> warning: The following are the actual parameters for the v2ray service startup.
> warning: Please make sure the configuration file path is correctly set.
> warning: The systemd version on the current operating system is too low.
> warning: Please consider to upgrade the systemd or the operating system.

- 有检查过两个JAVA的进程，都好好呆在进程中：

> root     26839  0.9 25.0 2127112 254128 pts/0  Sl   06:25   0:38 java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m /opt/jar/admin.j
> root     26851  0.4 17.5 2105548 177696 pts/0  Sl   06:25   0:19 java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m /opt/jar/v2ray-p

- 还没配置tls，所以端口设置的是80。理论上不应该出现这个问题，望大神解惑。

**Comment by master-coder-ll** [comment]
看出java进程输入的日志  /opt/jar/logs

**Comment by fuhailin** [comment]
遇到同样的问题，连接测试能显示时延，但无法走流量

**Comment by ckbkdj** [comment]
你去看看服务器时间,同步下服务器时间
