### ISSUE TITLE
多IP的VPS，怎么配套设置使用本管理插件呢？

### ISSUE THREAD

**Issue by jitashenshi** [master-coder-ll/v2ray-web-manager#162]
## 你的问题是什么？
我的VPS有多个公网IP，怎么配置使不同客户端用不同公网IP呢？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

**Comment by jitashenshi** [comment]
![image](https://user-images.githubusercontent.com/69400033/95184571-1fb36100-07fa-11eb-885a-37c623cc3c12.png)
请问就是在这里创建服务器，然后我有多个IP，就填在访问域名那里填不同IP就行了是吗？

**Comment by master-coder-ll** [comment]
是的，访问域名那里填不同IP就行
