### ISSUE TITLE
大量close_wait状态连接

### ISSUE THREAD

**Issue by zhaomanzhou** [master-coder-ll/v2ray-web-manager#165]
## 你的问题是什么？
服务器运行一段时间后，含有大量close_wait状态的连接
有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤
lsof -i
![image](https://user-images.githubusercontent.com/29169425/95706920-bb295380-0c8a-11eb-866d-5a4698b8c08b.png)

**Comment by master-coder-ll** [comment]
调整TCP close_wait 相关参数

**Comment by zhaomanzhou** [comment]
close_wait应该是客户端断开链接向服务端发第一个FIN包后，服务端一直没回第二个FIN包情况。对应程序应该是客户端断开连接后服务端没有调用close的情况

**Comment by master-coder-ll** [comment]
> close_wait应该是客户端断开链接向服务端发第一个FIN包后，服务端一直没回第二个FIN包情况。对应程序应该是客户端断开连接后服务端没有调用close的情况

确定这是一个bug，稍后会发一个版本修复
