### ISSUE TITLE
请问关于限速的问题，下行限速成功，上行无法限速吗？

### ISSUE THREAD

**Issue by Gangnamsstyle** [master-coder-ll/v2ray-web-manager#166]
## 你的问题是什么？
上行无法限速
有问题先搜索Issues
没找到相关问题
## 出现问题的情况是怎么样的？
问题同上
重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
希望能限制上传速度

**Comment by jitashenshi** [comment]
![image](https://user-images.githubusercontent.com/69400033/95934816-60b40280-0e04-11eb-9586-443a6338bc83.png)
