### ISSUE TITLE
服务器列表进行编辑后，提示“已经存在相同的域名”

### ISSUE THREAD

**Issue by matthuo333** [master-coder-ll/v2ray-web-manager#168]
## 你的问题是什么？

对已有服务器进行编辑，不成功。麻烦解决

## 出现问题的情况是怎么样的？

1. 选择 服务器列表
2. 从“上线”改为 “下线”
3. 点击 提交
4. 提示 已经存在相同的域名，  修改不成功。

## 期望结果？
能正常对服务器列表编辑及修改

P.S. 不确定我当前admin版本，在哪里查呢？

**Comment by master-coder-ll** [comment]
新版没发现这个问题

**Comment by matthuo333** [comment]
> 新版没发现这个问题

咋升级更新呢？应该可以平滑更新吧？ :)

**Comment by master-coder-ll** [comment]
> > 新版没发现这个问题
> 
> 咋升级更新呢？应该可以平滑更新吧？ :)

可以
