### ISSUE TITLE
admin与proxy进程无法同时启动

### ISSUE THREAD

**Issue by scarrrr316** [master-coder-ll/v2ray-web-manager#173]
## 你的问题是什么？

admin与proxy进程无法同时启动

## 出现问题的情况是怎么样的？

无论先启动哪个服务,只要是有2个服务就会Exit 127 报错 
```
[root@sacr-v2ray v2ray]# nohup java -jar -Xms100m -Xmx100m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m  /o
pt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1 &
[1] 1953
[root@sacr-v2ray v2ray]# nohup java -jar -Xms100m -Xmx100m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m /op
t/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &
[2] 1960
[1]   Exit 127                nohup java -jar -Xms100m -Xmx100m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80
m /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1
```
内存已经设置到100m , 运行setsebool httpd_can_network_connect 1 之后显示 SELinux is disabled ,然后我就把SELinux改成enforcing然后重启再试,还是同样的结果Exit 127 ,再次输入 setsebool httpd_can_network_connect 1 还是没用

## 相关日志 java服务日志位于/opt/jar/logs

查了一下根本没有logs文件,没任何运行日志,啊这

## 期望结果？

能同时启动,登入面板(502)

**Comment by scarrrr316** [comment]
我发现只有centos7有这个问题,我弄了很久, 包含2次宝塔版本2次手动配置nginx ,发现都是127报错,但是ubuntu 一次就成了 啊这

**Comment by master-coder-ll** [comment]
建议 使用 ubuntu 或者 debian 系统安装
