### ISSUE TITLE
dashboard只是装饰用途吗?

### ISSUE THREAD

**Issue by scarrrr316** [master-coder-ll/v2ray-web-manager#174]
## 你的问题是什么？

dashboard只是装饰用途吗, 为啥数据都是固定的没有变化

## 期望结果？

能正常显示数据用量等等

**Comment by master-coder-ll** [comment]
> ## 你的问题是什么？
> dashboard只是装饰用途吗, 为啥数据都是固定的没有变化
> 
> ## 期望结果？
> 能正常显示数据用量等等

被你发现了👏

**Comment by scarrrr316** [comment]
嗯？？啊这,,,,,,,我还以为是我没用梯子所以没更新数据

> > ## 你的问题是什么？
> > dashboard只是装饰用途吗, 为啥数据都是固定的没有变化
> > ## 期望结果？
> > 能正常显示数据用量等等
> 
> 被你发现了👏
