### ISSUE TITLE
v2ray-proxy进程 用段时间，cpu就占用彪高

### ISSUE THREAD

**Issue by doutuo** [master-coder-ll/v2ray-web-manager#175]
下的最新的3.1.8  以前老版本也会这样，就是用段时间，CPU就占用高，连接的ip在10几个，基本每天我都要删掉进程，重新运行一次。

**Comment by master-coder-ll** [comment]
截图哈

**Comment by doutuo** [comment]
[![Dajg78.md.png](https://s3.ax1x.com/2020/11/25/Dajg78.md.png)](https://imgchr.com/i/Dajg78)
其它的我刚结束了，现在就一直占用在40%左右，过段时间就五六十，高了，就容易网络断，不流畅。

**Comment by master-coder-ll** [comment]
> [![Dajg78.md.png](https://camo.githubusercontent.com/e464c8d661e6b68ee864bcf39527efc5af0d05c290b386ca6376ba08bf22f959/68747470733a2f2f73332e617831782e636f6d2f323032302f31312f32352f44616a6737382e6d642e706e67)](https://imgchr.com/i/Dajg78)
> 其它的我刚结束了，现在就一直占用在40%左右，过段时间就五六十，高了，就容易网络断，不流畅。

你这图， 看不清。

1. 用户量多少

2. 多少内存

3. 是否存在第三个java 进程

**Comment by doutuo** [comment]
[![Dd5YQS.md.png](https://s3.ax1x.com/2020/11/25/Dd5YQS.md.png)](https://imgchr.com/i/Dd5YQS)
我用的是外链图片，要看清楚图片的话，你点击下图片就可以跳到图片站，可以看得很清晰。
1、在线用户数大概在几个~10几个之间。
2、配置好几种，但都有这个proxy的Java进程占用cpu高。配置有CPU：1核  2核  3核 内存有1G 2G的。
3、没有第三个java进程，只有proxy和admin两个进程，admin的进程正常，proxy的用段时间cpu就彪起来了。

**Comment by doutuo** [comment]
[![Dd5YQS.png](https://s3.ax1x.com/2020/11/25/Dd5YQS.png)](https://imgchr.com/i/Dd5YQS)

**Comment by master-coder-ll** [comment]
内存有1G嘛？修改 v2ray-proxy 参数试试： -Xms50m -Xmx200m -XX:MaxDirectMemorySize=50M

**Comment by doutuo** [comment]
已将参数修改，等待有情况再反应。
proxy报错在哪查看？正常的这个进程cpu的占用情况是多少？人数在几人~10几人在线的时候。

**Comment by zhaomanzhou** [comment]
+1，用top -H发现两个线程占用比较高，用jstack显示这两个线程是netty的worker线程
<img width="997" alt="mmexport1607159063856" src="https://user-images.githubusercontent.com/29169425/101238563-0f493500-371c-11eb-8c44-27b47755e609.png">

CPU飙升图
![Screenshot_20201205_170626](https://user-images.githubusercontent.com/29169425/101238599-3a338900-371c-11eb-8285-7d10ab937281.jpg)降下去的时候是因为重启服务了

**Comment by lawrence1751** [comment]
最近也發生這個問題，目前有兩台都是掛一樣的v2proxy，使用人數最多同時3位

一台常發生，另一台反而沒事，但是java給兩台的參數都是openj9的參數

都是1vCPU+512 MB RAM

`nohup /root/jdk8u275-b01-jre/bin/java -jar   -Xmx35m -Xiss64k -Xss320k -XcompilationThreads1 -XX:+UseCompressedOops -verbose:sizes -XX:MaxDirectMemorySize=10M  -XX:MaxMetaspaceSize=70m  -Xscmx60M -Xscmaxaot8M -Xquickstart /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml  > /dev/null 2>&1`

感覺執行java約60小時以上就會出現這個問題，RAM則正常

附上htop截圖

如果又再遇到狀況時將附上error log
<img width="878" alt="螢幕快照 2021-01-06 下午11 20 35" src="https://user-images.githubusercontent.com/51253739/104462950-22d59e80-55ec-11eb-9d11-95d362977ecf.png">

**Comment by lawrence1751** [comment]
`-Xms50m -Xmx200m -XX:MaxDirectMemorySize=50M`
使用上面這組參數撐約60個小時會達到40~50%的CPU使用率
只好重開proxy服務才可以恢復正常

期待有其他解法

**Comment by lawrence1751** [comment]
伺服器版本 Ubuntu 18.04.5 LTS
1 vCPU
512MB RAM
SWAP 500M

v2ray-proxy版本 3.1.8

JAVA 版本: OpenJDK8U-jre_x64_linux_openj9_8u275b01_openj9-0.23.0


設定參數:

```
#!/bin/sh
nohup /root/jdk8u275-b01-jre/bin/java -jar   -Xms50m -Xmx200m -Xiss64k -Xss320k -XcompilationThreads1 -XX:+UseCompressedOops -verbose:sizes -XX:MaxDirectMemorySize=50M  -XX:MaxMetaspaceSize=70m  -Xscmx60M -Xscmaxaot8M -Xquickstart /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml  > /dev/null 2>&1 &
echo $! > /var/run/v2ray-proxy.pid
```

同時使用人數最高3人，平常約2人同時使用，無大拉頻寬習慣

JAVA開v2proxy沒多久就會飆到80%



附上ERROR.LOG

2021-01-31 14:16:55.698 ERROR 5042 --- [worker-3-1] c.j.f.proxy.handler.ReceiverHandler      :  Receiver exceptionCaught:

java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at io.netty.buffer.UnpooledDirectByteBuf.setBytes(UnpooledDirectByteBuf.java:575)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:823)

試過下列參數但無效：

```
nohup java -jar   -Xmx35m -Xiss64k -Xss320k -XcompilationThreads1 -XX:+UseCompressedOops -verbose:sizes -XX:MaxDirectMemorySize=10M  -XX:MaxMetaspaceSize=70m  -Xscmx60M -Xscmaxaot8M -Xquickstart /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml  > /dev/null 2>&1 &

nohup java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &
```
htop狀況如下
<img width="1432" alt="螢幕快照 2021-01-31 下午2 21 49" src="https://user-images.githubusercontent.com/51253739/106376611-f5516900-63d1-11eb-9376-7461ac0b462a.png">

@master-coder-ll 

謝謝！

**Comment by Misaka1008611** [comment]
可以尝试一下 我在另一个issue下的回复，我这边修改后已经连续一周CPU占用低于10%了

https://github.com/master-coder-ll/v2ray-web-manager/issues/169

**Comment by ocswor** [comment]
大佬，看看这个问题能解决么，目前这个问题好频繁

**Comment by ocswor** [comment]
> > [![Dajg78.md.png](https://camo.githubusercontent.com/e464c8d661e6b68ee864bcf39527efc5af0d05c290b386ca6376ba08bf22f959/68747470733a2f2f73332e617831782e636f6d2f323032302f31312f32352f44616a6737382e6d642e706e67)](https://imgchr.com/i/Dajg78)
> > 其它的我刚结束了，现在就一直占用在40%左右，过段时间就五六十，高了，就容易网络断，不流畅。
> 
> 你这图， 看不清。
> 
> 1. 用户量多少
> 2. 什么配置
> 3. 是否存在第三个java 进程

大佬 我发下一个新情况，就是当一个账号的链接数，超过200，cpu就会飙升

看看能修复么
