### ISSUE TITLE
无法管理proxy节点流量周期速度等属性

### ISSUE THREAD

**Issue by whoamiiiii** [master-coder-ll/v2ray-web-manager#176]
我用管理员账号把用户账号的状态设置为禁用, 显示红字, 但是依然可以连接proxy节点, 而且限速限流什么的没有效果
是我的使用方法有错么, 劳驾大佬解答下

**Comment by master-coder-ll** [comment]
> 我用管理员账号把用户账号的状态设置为禁用, 显示红字, 但是依然可以连接proxy节点, 而且限速限流什么的没有效果
> 是我的使用方法有错么, 劳驾大佬解答下

1. 禁用并不会马上生效，有约5分钟缓存
