### ISSUE TITLE
纯粹支持一下作者,终于找到java版的了.

### ISSUE THREAD

**Issue by HiColinn** [master-coder-ll/v2ray-web-manager#178]
## 你的问题是什么？

无问题,纯粹来支持一下!

目前市面上的其它几个v2ray面板,基本上都是前端面板免费,后端收费.
而且基本上都是基于php开发的,对于java用户来讲,完全无法下手.

这个项目前端目测是avue,应该是前后端分离的,后端对java选手来说终于可以玩一玩了~

希望作者能保持java项目开开源传统,
可以在readme挂出捐赠渠道,作者加油.

**Comment by goatlove** [comment]
作者怕喝茶，不敢贴捐赠。可以试试不知名加密货币钱包地址捐赠

**Comment by master-coder-ll** [comment]
多谢各位，暂时不需要哈，也怕请喝茶

**Comment by D36u99er** [comment]
> 多谢各位，暂时不需要哈，也怕请喝茶
忍住笑出了猪叫声，很感谢大佬的分享。加个飞机吗，付费地址啥的吗。飞机  @sandy3306
