### ISSUE TITLE
后台添加公告导致内存溢出

### ISSUE THREAD

**Issue by goatlove** [master-coder-ll/v2ray-web-manager#179]
## 你的问题是什么？
后台添加2则公告，出现内存溢出错误提示。
Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space

有问题先搜索Issues

## 出现问题的情况是怎么样的？
添加第1则公告，大约几百字和上传插入一张200KB大小图片，点击公告列表，可正常渲染出来。
添加第2则公告，大约几十字和上传插入4张200KB大小图片，点击公告列表，提示java.lang.OutOfMemoryError: Java heap space内存溢出。后台点击其他栏显示正常，代理控制正常。

系统1核2G内存，采用openj9-jvm运行。

原参数 nohup java -jar  -Xmx50m -Xiss64k -Xss320k -XcompilationThreads1 -XX:+UseCompressedOops -verbose:sizes -XX:MaxDirectMemorySize=20M -XX:MetaspaceSize=50M -XX:MaxMetaspaceSize=100m -Xscmx60M -Xscmaxaot8M -Xquickstart

尝试将 -Xmx50m 增加至  -Xmx500m 重启系统，点击公告列表，不再提示内存溢出错误，但始终提示5000ms超时，无法展现公告内容。后台点击其他栏显示正常，代理控制正常。

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
公告正常显示或者延长超时时限。

**Comment by goatlove** [comment]
最新情况：出现问题是昨天深夜，刚刚又试了一下，登录点击公告列表，都可以展现出来了，估计昨天晚上网络慢5秒内无法完全渲染出来？不过，2则公告都是默认展开全文，并没有折叠，希望能默认折叠只展示公告标题。或者，延长一下超时时限？

**Comment by goatlove** [comment]
看了下，4张上传图片的加密链接地址使得公告字符多大117万，删除这4张图，实际只有1000多个字符，等晚上把图片地址改为本地链接再试试。

**Comment by master-coder-ll** [comment]
> 看了下，4张上传图片的加密链接地址使得公告字符多大117万，删除这4张图，实际只有1000多个字符，等晚上把图片地址改为本地链接再试试。

使用图片地址解决
