### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by yikale** [master-coder-ll/v2ray-web-manager#18]

**Comment by master-coder-ll** [comment]
那一步出现问题，相关日志:/opt/jar/logs

**Comment by yikale** [comment]
已经解决了，谢谢。之前是因为nginx报错了，再请教个问题，443该怎么配置呢

**Comment by master-coder-ll** [comment]
> 已经解决了，谢谢。之前是因为nginx报错了，再请教个问题，443该怎么配置呢

google 免费tls

**Comment by yikale** [comment]
发现账号到期和流量统计不生效
![微信截图_20200220152046](https://user-images.githubusercontent.com/29316179/74910099-b0b50380-53f4-11ea-9864-2fecf493245d.png)

**Comment by master-coder-ll** [comment]
> 发现账号到期和流量统计不生效
> ![微信截图_20200220152046](https://user-images.githubusercontent.com/29316179/74910099-b0b50380-53f4-11ea-9864-2fecf493245d.png)
你的账号访问过吗？

**Comment by master-coder-ll** [comment]
> > 发现账号到期和流量统计不生效
> > ![微信截图_20200220152046](https://user-images.githubusercontent.com/29316179/74910099-b0b50380-53f4-11ea-9864-2fecf493245d.png)
 
 你的账号访问过吗？同时低于10MB以下的流量不显示

**Comment by yikale** [comment]
每个账号都访问测试过

**Comment by yikale** [comment]
重启服务器后访问提示Request failed with status code 502

**Comment by master-coder-ll** [comment]
> 重启服务器后访问提示Request failed with status code 502

重启服务器，重新打开java服务。或者做成开机启动
