### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by l42111996** [master-coder-ll/v2ray-web-manager#180]
addProxyAccount error:UNKNOWN: v2ray.com/core/app/proxyman/command: failed to get handler: 1 > v2ray.com/core/app/proxyman/inbound: handler not found: 1,{"version":1608198092258,"accountId":30,"host":"xxx.xxx.xxx.xxx","accountNo":"dey3jp5","id":"01194a16-fc5a-4471-8359-63bcbcfad569","alterId":64,"level":0,"email":"ceshi@qq.com","inBoundTag":"1","upTrafficLimit":1024,"downTrafficLimit":1024,"maxConnection":64,"v2rayHost":"127.0.0.1","v2rayPort":6001,"v2rayManagerPort":62789,"proxyIp":"127.0.0.1"}

最新版本出现了这个错误，有什么好的解决方案吗？

**Comment by master-coder-ll** [comment]
你是更新了V2RAY 吧， 最简单的方法重启
