### ISSUE TITLE
ws path 路径不能修改?只能用默认的 /ws/%s/ 吗？

### ISSUE THREAD

**Issue by doutuo** [master-coder-ll/v2ray-web-manager#181]
如题，当修改默认的ws路径，就会上不了网，只能用 默认的路径  /ws/%s/
像把/ws删除，或改成 /ws/%s   未尾的 "/" 去掉，再生成的 vmess 都不可以上网

**Comment by master-coder-ll** [comment]
可以，最少要一个%s

**Comment by yockrain** [comment]
可否提示一下这个参数 %s 运行的机制或者原理
如果可以，我想通过自己在后台修改某些配置文件，希望能够把A账号对应的多台服务器的"路径(path)"设置成一样的
谢谢~
