### ISSUE TITLE
修改访问域名会导致ws路径改变。

### ISSUE THREAD

**Issue by shenmirenQUQ** [master-coder-ll/v2ray-web-manager#183]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
例如我把节点的IP改为域名后，这个节点的所有ws路径都变了。
可以设置未不变吗

**Comment by master-coder-ll** [comment]
不能， /ws/后面的数据有签名功能
