### ISSUE TITLE
ERROR 708 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

### ISSUE THREAD

**Issue by shenmirenQUQ** [master-coder-ll/v2ray-web-manager#187]
第二 第三台vps成功部署对接主vps。可以正常上网。但是重启后无法再次启动v2ray-proxy。

使用# 查看v2ray-proxy的错误日志(version > v3.1.5)
tail -100f /opt/jar/logs/v2ray-proxy.log.ERROR
输出错误如下
***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8091 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8091, or configure this application to listen on another port.

**Comment by shenmirenQUQ** [comment]
主服务器正常上网，中转也没问题。
但是第二 第三台无法对接上了

**Comment by master-coder-ll** [comment]
The port may already be in use or the connector may be misconfigured.

> 主服务器正常上网，中转也没问题。
> 但是第二 第三台无法对接上了

The port may already be in use or the connector may be misconfigured.

**Comment by shenmirenQUQ** [comment]
> 该端口可能已在使用中，或者连接器配置错误。
> 
> > 主服务器正常上网，中转也没问题。
> > 但是第二第三台无法对接上了
> 
> 该端口可能已在使用中，或者连接器配置错误。
> 
> 1. 重复启动
> 2. 占有被占有

——
大佬还有一个问题，搭建的时候忘记修改authPassword密码，用的是默认空的，自己尝试过修改，但是修改后会导致之前的用户无法连接，有办法在不影响之前的用户情况下修改这个authPassword吗？
