### ISSUE TITLE
内存泄漏导致proxy异常

### ISSUE THREAD

**Issue by lucfiar** [master-coder-ll/v2ray-web-manager#191]
## 你的问题是什么？

proxy中间件存在内存泄漏

## 出现问题的情况是怎么样的？

30用户左右，进行大量下载操作后，proxy端会挂掉，nginx log中为502 Error。重启proxy后恢复正常。

## 相关日志 java服务日志位于/opt/jar/logs

- 启动参数
nohup /root/bin/jdk-9.0.4+12/bin/java -jar -Xmx35m -Xiss64k -Xss320k -XcompilationThreads1 -XX:+UseCompressedOops -verbose:sizes -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m -Xscmx60M -Xscmaxaot8M -Xquickstart /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &
- nginx log
[FILTERED] - - [19/Mar/2021:11:25:12 +0800] "GET /uplink/[FILTERED]/ HTTP/1.1" 502 150 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27" "-"
[FILTERED] - - [19/Mar/2021:11:25:12 +0800] "GET /uplink/[FILTERED]/ HTTP/1.1" 502 150 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27" "-"
[FILTERED] - - [19/Mar/2021:11:25:12 +0800] "GET /uplink/[FILTERED]/ HTTP/1.1" 502 150 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27" "-"
[FILTERED] - - [19/Mar/2021:11:25:12 +0800] "GET /uplink/[FILTERED]/ HTTP/1.1" 502 150 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27" "-"
[FILTERED] - - [19/Mar/2021:11:25:13 +0800] "GET /uplink/[FILTERED]/ HTTP/1.1" 502 150 "-" "Go-http-client/1.1" "-"
[FILTERED] - - [19/Mar/2021:11:25:14 +0800] "GET /uplink/[FILTERED]/ HTTP/1.1" 502 150 "-" "Go-http-client/1.1" "-"

- Java 错误日志
0SECTION       TITLE subcomponent dump routine
NULL           ===============================
1TICHARSET     UTF-8
1TISIGINFO     Dump Event "systhrow" (00040000) Detail "java/lang/OutOfMemoryError" "Java heap space" received 
1TIDATETIME    Date: 2021/03/18 at 22:05:18:530
1TINANOTIME    System nanotime: 6827481914629656
1TIFILENAME    Javacore filename:    //javacore.20210318.220518.22992.0012.txt
1TIREQFLAGS    Request Flags: 0x81 (exclusive+preempt)
1TIPREPSTATE   Prep State: 0x104 (exclusive_vm_access+trace_disabled)
NULL           ------------------------------------------------------------------------
0SECTION       GPINFO subcomponent dump routine
NULL           ================================
2XHOSLEVEL     OS Level         : Linux 4.11.8-1.el7.elrepo.x86_64
2XHCPUS        Processors -
3XHCPUARCH       Architecture   : amd64
3XHNUMCPUS       How Many       : 1
3XHNUMASUP       NUMA is either not supported or has been disabled by user
NULL           
1XHERROR2      Register dump section only produced for SIGSEGV, SIGILL or SIGFPE.
NULL           
NULL           ------------------------------------------------------------------------
0SECTION       ENVINFO subcomponent dump routine
NULL           =================================
1CIJAVAVERSION JRE 9 Linux amd64-64 (build 9.0.4-adoptopenjdk+12)
1CIVMVERSION   20180814_248
1CIJ9VMTAG     openj9-0.9.0
1CIJ9VMVERSION 24e53631
1CIJITVERSION  24e53631
1CIOMRVERSION  fad6bf6e_CMPRSS
1CIJCLVERSION  feec4d2ae based on jdk-9.0.4+12
1CIJITMODES    JIT enabled, AOT enabled, FSD disabled, HCR enabled
1CIRUNNINGAS   Running as a standalone JVM
1CIVMIDLESTATE VM Idle State: ACTIVE
1CISTARTTIME   JVM start time: 2021/03/09 at 13:15:45:914
1CISTARTNANO   JVM start nanotime: 6018109298835497
1CIPROCESSID   Process ID: 22992 (0x59D0)
1CICMDLINE     [not available]
1CIJAVAHOMEDIR Java Home Dir:   /root/bin/jdk-9.0.4+12
1CIJAVADLLDIR  Java DLL Dir:    /root/bin/jdk-9.0.4+12/bin
1CISYSCP       Sys Classpath:   
1CIUSERARGS    UserArgs:
2CIUSERARG               -Xoptionsfile=/root/bin/jdk-9.0.4+12/lib/options.default
2CIUSERARG               -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple
2CIUSERARG               -Xjcl:jclse9_29
2CIUSERARG               -Dcom.ibm.oti.vm.bootstrap.library.path=/root/bin/jdk-9.0.4+12/lib/compressedrefs:/root/bin/jdk-9.0.4+12/lib
2CIUSERARG               -Dsun.boot.library.path=/root/bin/jdk-9.0.4+12/lib/compressedrefs:/root/bin/jdk-9.0.4+12/lib
2CIUSERARG               -Djava.library.path=/root/bin/jdk-9.0.4+12/lib/compressedrefs:/root/bin/jdk-9.0.4+12/lib:/usr/lib64:/usr/lib
2CIUSERARG               -Djava.home=/root/bin/jdk-9.0.4+12
2CIUSERARG               -Duser.dir=/
2CIUSERARG               -Xmx35m
2CIUSERARG               -Xiss64k
2CIUSERARG               -Xss320k
2CIUSERARG               -XcompilationThreads1
2CIUSERARG               -XX:+UseCompressedOops
2CIUSERARG               -verbose:sizes
2CIUSERARG               -XX:MaxDirectMemorySize=10M
2CIUSERARG               -Dsun.nio.MaxDirectMemorySize=10485760
2CIUSERARG               -XX:MaxMetaspaceSize=80m
2CIUSERARG               -Xscmx60M
2CIUSERARG               -Xscmaxaot8M
2CIUSERARG               -Xquickstart
2CIUSERARG               -Djava.class.path=/opt/jar/v2ray-proxy.jar
2CIUSERARG               -Dsun.java.command=/opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml
2CIUSERARG               -Dsun.java.launcher=SUN_STANDARD
2CIUSERARG               -Dsun.java.launcher.pid=22992
NULL
1CIUSERLIMITS  User Limits (in bytes except for NOFILE and NPROC)
NULL           ------------------------------------------------------------------------
NULL           type                            soft limit           hard limit
2CIUSERLIMIT   RLIMIT_AS                        unlimited            unlimited
2CIUSERLIMIT   RLIMIT_CORE                      unlimited            unlimited
2CIUSERLIMIT   RLIMIT_CPU                       unlimited            unlimited
2CIUSERLIMIT   RLIMIT_DATA                      unlimited            unlimited
2CIUSERLIMIT   RLIMIT_FSIZE                     unlimited            unlimited
2CIUSERLIMIT   RLIMIT_LOCKS                     unlimited            unlimited
2CIUSERLIMIT   RLIMIT_MEMLOCK                       65536                65536
2CIUSERLIMIT   RLIMIT_NOFILE                         1024                 4096
2CIUSERLIMIT   RLIMIT_NPROC                          3879                 3879
2CIUSERLIMIT   RLIMIT_RSS                       unlimited            unlimited
2CIUSERLIMIT   RLIMIT_STACK                       8388608            unlimited
2CIUSERLIMIT   RLIMIT_MSGQUEUE                     819200               819200
2CIUSERLIMIT   RLIMIT_NICE                              0                    0
2CIUSERLIMIT   RLIMIT_RTPRIO                            0                    0
2CIUSERLIMIT   RLIMIT_SIGPENDING                     3879                 3879
NULL
1CIENVVARS     Environment Variables
NULL           ------------------------------------------------------------------------
2CIENVVAR      SHELL=/bin/sh
2CIENVVAR      USER=root
2CIENVVAR      PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
2CIENVVAR      PWD=/
2CIENVVAR      LANG=en_US.UTF-8
2CIENVVAR      SHLVL=1
2CIENVVAR      HOME=/root
2CIENVVAR      LOGNAME=root
2CIENVVAR      _=/usr/bin/nohup
NULL           
1CISYSINFO     System Information
NULL           ------------------------------------------------------------------------
2CISYSINFO     Hypervisor name = KVM
2CISYSINFO     /proc/sys/kernel/core_pattern = core
2CISYSINFO     /proc/sys/kernel/core_uses_pid = 1
NULL           
1CICPUINFO     CPU Information
NULL           ------------------------------------------------------------------------
2CIPHYSCPU     Physical CPUs: 1
2CIONLNCPU     Online CPUs: 1
2CIBOUNDCPU    Bound CPUs: 1
2CITARGETCPU   Target CPUs: 1
NULL           
NULL           ------------------------------------------------------------------------
0SECTION       NATIVEMEMINFO subcomponent dump routine
NULL           =================================
0MEMUSER
1MEMUSER       JRE: 572,845,256 bytes / 11590 allocations
1MEMUSER       |
2MEMUSER       +--VM: 290,918,552 bytes / 7974 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 46,397,216 bytes / 2409 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 39,404,072 bytes / 725 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 36,761,600 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 2,642,472 bytes / 724 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Threads: 12,321,288 bytes / 209 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Stack: 2,275,440 bytes / 30 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Native Stack: 9,699,328 bytes / 31 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 346,520 bytes / 148 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Trace: 502,864 bytes / 1586 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JVMTI: 17,776 bytes / 13 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JNI: 603,088 bytes / 1577 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Port Library: 190,526,320 bytes / 96 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Unused <32bit allocation regions: 190,512,952 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 13,368 bytes / 95 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 1,145,928 bytes / 1359 allocations
1MEMUSER       |
2MEMUSER       +--JIT: 280,889,024 bytes / 1194 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 268,435,456 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 4,194,432 bytes / 2 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 8,259,136 bytes / 1191 allocations
1MEMUSER       |
2MEMUSER       +--Class Libraries: 461,648 bytes / 50 allocations
2MEMUSER       |  |
3MEMUSER       |  +--VM Class Libraries: 461,648 bytes / 50 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--sun.misc.Unsafe: 450,072 bytes / 34 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Direct Byte Buffers: 76,408 bytes / 25 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Other: 373,664 bytes / 9 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 11,576 bytes / 16 allocations
1MEMUSER       |
2MEMUSER       +--Unknown: 576,032 bytes / 2372 allocations

**Comment by master-coder-ll** [comment]
30用户左右，进行大量下载操作后  -Xmx35m   大点拉， 你的vps 多少内存 ？

**Comment by lucfiar** [comment]
内存1G 已经修改了配置这几天再跑跑看，感谢感谢感谢！

**Comment by lucfiar** [comment]
您好，问题还是会出现，只不过调大Xmx后，正常工作的时间变长了，可能还是存在了泄露？ 下面是这次的log信息。
## 启动参数（-Xmx已改为100m）
/bin/java -jar -Xmx100m -Xiss64k -Xss320k -XcompilationThreads1 -XX:+UseCompressedOops -verbose:sizes -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m -Xscmx60M -Xscmaxaot8M -Xquickstart /opt/jar/v2ray-proxy.jar

> 1TICHARSET     UTF-8
1TISIGINFO     Dump Event "systhrow" (00040000) Detail "java/lang/OutOfMemoryError" "Java heap space" received
1TIDATETIME    Date: 2021/04/21 at 14:58:29:804
1TINANOTIME    System nanotime: 9739473188753773
1TIFILENAME    Javacore filename:    //javacore.20210421.145808.4673.0003.txt
1TIREQFLAGS    Request Flags: 0x81 (exclusive+preempt)
1TIPREPSTATE   Prep State: 0x104 (exclusive_vm_access+trace_disabled)
NULL           ------------------------------------------------------------------------
0SECTION       GPINFO subcomponent dump routine
NULL           ================================
2XHOSLEVEL     OS Level         : Linux 4.11.8-1.el7.elrepo.x86_64
2XHCPUS        Processors -
3XHCPUARCH       Architecture   : amd64
3XHNUMCPUS       How Many       : 1
3XHNUMASUP       NUMA is either not supported or has been disabled by user
NULL
1XHERROR2      Register dump section only produced for SIGSEGV, SIGILL or SIGFPE.
NULL
NULL           ------------------------------------------------------------------------
0SECTION       ENVINFO subcomponent dump routine
NULL           =================================
1CIJAVAVERSION JRE 9 Linux amd64-64 (build 9.0.4-adoptopenjdk+12)
1CIVMVERSION   20180814_248
1CIJ9VMTAG     openj9-0.9.0
1CIJ9VMVERSION 24e53631
1CIJITVERSION  24e53631
1CIOMRVERSION  fad6bf6e_CMPRSS
1CIJCLVERSION  feec4d2ae based on jdk-9.0.4+12
1CIJITMODES    JIT enabled, AOT enabled, FSD disabled, HCR enabled
1CIRUNNINGAS   Running as a standalone JVM
1CIVMIDLESTATE VM Idle State: ACTIVE
1CISTARTTIME   JVM start time: 2021/03/23 at 18:44:09:580
1CISTARTNANO   JVM start nanotime: 7247412964463250
1CIPROCESSID   Process ID: 4673 (0x1241)
1CICMDLINE     [not available]
1CIJAVAHOMEDIR Java Home Dir:   /root/bin/jdk-9.0.4+12
1CIJAVADLLDIR  Java DLL Dir:    /root/bin/jdk-9.0.4+12/bin
1CISYSCP       Sys Classpath:
1CIUSERARGS    UserArgs:
2CIUSERARG               -Xoptionsfile=/root/bin/jdk-9.0.4+12/lib/options.default
2CIUSERARG               -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple
2CIUSERARG               -Xjcl:jclse9_29
2CIUSERARG               -Dcom.ibm.oti.vm.bootstrap.library.path=/root/bin/jdk-9.0.4+12/lib/compressedrefs:/root/bin/jdk-9.0.4+12/lib
2CIUSERARG               -Dsun.boot.library.path=/root/bin/jdk-9.0.4+12/lib/compressedrefs:/root/bin/jdk-9.0.4+12/lib
2CIUSERARG               -Djava.library.path=/root/bin/jdk-9.0.4+12/lib/compressedrefs:/root/bin/jdk-9.0.4+12/lib:/usr/lib64:/usr/lib
2CIUSERARG               -Djava.home=/root/bin/jdk-9.0.4+12
2CIUSERARG               -Duser.dir=/
2CIUSERARG               -Xmx100m
2CIUSERARG               -Xiss64k
2CIUSERARG               -Xss320k
2CIUSERARG               -XcompilationThreads1
2CIUSERARG               -XX:+UseCompressedOops
2CIUSERARG               -verbose:sizes
2CIUSERARG               -XX:MaxDirectMemorySize=10M
2CIUSERARG               -Dsun.nio.MaxDirectMemorySize=10485760
2CIUSERARG               -XX:MaxMetaspaceSize=80m
2CIUSERARG               -Xscmx60M
2CIUSERARG               -Xscmaxaot8M
2CIUSERARG               -Xquickstart
2CIUSERARG               -Djava.class.path=/opt/jar/v2ray-proxy.jar
2CIUSERARG               -Dsun.java.command=/opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml
2CIUSERARG               -Dsun.java.launcher=SUN_STANDARD
2CIUSERARG               -Dsun.java.launcher.pid=4673


## NATIVEMEMINFO部分的log
> NULL           ------------------------------------------------------------------------
0SECTION       NATIVEMEMINFO subcomponent dump routine
NULL           =================================
0MEMUSER
1MEMUSER       JRE: 646,363,792 bytes / 10722 allocations
1MEMUSER       |
2MEMUSER       +--VM: 361,174,712 bytes / 6707 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 46,456,152 bytes / 2409 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 109,819,672 bytes / 728 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 104,919,040 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 4,900,632 bytes / 727 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Threads: 12,359,256 bytes / 213 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Stack: 2,275,440 bytes / 30 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Native Stack: 9,699,328 bytes / 31 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 384,488 bytes / 152 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Trace: 308,064 bytes / 309 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JVMTI: 17,776 bytes / 13 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JNI: 607,616 bytes / 1583 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Port Library: 190,459,640 bytes / 93 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Unused <32bit allocation regions: 190,446,904 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 12,736 bytes / 92 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 1,146,536 bytes / 1359 allocations
1MEMUSER       |
2MEMUSER       +--JIT: 284,169,528 bytes / 1451 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 268,435,456 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 6,291,648 bytes / 3 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 9,442,424 bytes / 1447 allocations
1MEMUSER       |
2MEMUSER       +--Class Libraries: 443,520 bytes / 192 allocations
2MEMUSER       |  |
3MEMUSER       |  +--VM Class Libraries: 443,520 bytes / 192 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--sun.misc.Unsafe: 384,136 bytes / 32 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Direct Byte Buffers: 10,472 bytes / 23 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Other: 373,664 bytes / 9 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 59,384 bytes / 160 allocations
1MEMUSER       |
2MEMUSER       +--Unknown: 576,032 bytes / 2372 allocations
NULL

**Comment by lucfiar** [comment]
![image](https://user-images.githubusercontent.com/80940904/115549225-f4e2b300-a2da-11eb-974a-b007a7279321.png)

**Comment by master-coder-ll** [comment]
-xmx200m -xss512k   继续调大
