### ISSUE TITLE
集群分散式负载，admin端无法控制Proxy节点。

### ISSUE THREAD

**Issue by doutuo** [master-coder-ll/v2ray-web-manager#195]
你好，照教程 设置好Proxy节点端。修改好Proxy.yaml。
在admin端面板创建Proxy节点服务器，生成vmess后，导入客户端，可以正常上网。

问题：当我在admin面板，修改账号的到期时间或速率等限制，但Proxy端无效果。
例如：修改时间到期，时间为红色。Proxy节点无效果，可以继续上网。等了几十分钟也无生效。
修改速率=1，Proxy节点也没影响，上网速度也没改变。

只能在Proxy节点端，结束v2ray-proxy进程，重新启动v2ray-proxy进程，限制才会生效。
请问这个是我哪设置错误了吗？

**Comment by doutuo** [comment]
<img src = 'https://ftp.bmp.ovh/imgs/2021/03/7b82f2599dfedd97.png' />
admin端配置节点如图所示

**Comment by doutuo** [comment]
我知道了，测试成功了。 admin端的 中间件地址，要填 Proxy端的ip或域名才可。

**Comment by json9666** [comment]
想问下，路径 我这里 如果自动生成的服务器 路径 /ws/accountnoxxxxx  但是v2ray path 配置的是 /ws/ 
nginx location 配置的是/ws/ 但是无法连接成功，想问下你有这个问题吗？

**Comment by mrgorungo** [comment]
https://github.com/master-coder-ll/v2ray-web-manager/blob/master/step-by-step-model.md

请问，按照这里的第一模式说明，是不是中间件地址应该写本地(127.0.0.1)？

**Comment by mrgorungo** [comment]
问题解决了，

**Comment by WeiMXi** [comment]
> 我知道了，测试成功了。 admin端的 中间件地址，要填 Proxy端的ip或域名才可。

这个中间件地址可以使用https的url吗？
