### ISSUE TITLE
搞不清目录结构

### ISSUE THREAD

**Issue by timesons** [master-coder-ll/v2ray-web-manager#2]
对比了很多个版本，觉得你这个挺好的，只是wiki 对新手太不友好了，对文章中的应该在哪个目录下操作搞不清，尝试失败～

**Comment by master-coder-ll** [comment]
你可以先`star`,过1/2天改进下，你也可以提下意见。

**Comment by master-coder-ll** [comment]
updated

**Comment by timesons** [comment]
有开放用户注册的功能吗？我好像没找到连接sql的地方

**Comment by timesons** [comment]
![image](https://user-images.githubusercontent.com/9979023/71793839-98259f80-3079-11ea-9ca2-013708a8af74.png)

**Comment by master-coder-ll** [comment]
mkdir /opt/jar/db -p 

java 智能的地方,动态生成sql

**Comment by timesons** [comment]
> mkdir /opt/jar/db -p
> 
> java 智能的地方,动态生成sql

部属完了，访问域名没有反应

**Comment by master-coder-ll** [comment]
server_name _; #或者域名

**Comment by master-coder-ll** [comment]
server_name _; #或者域名

**Comment by timesons** [comment]
> server_name _; #或者域名
![image](https://user-images.githubusercontent.com/9979023/71902596-60177d00-319d-11ea-9c37-4f7515629069.png)

**Comment by timesons** [comment]
> server_name _; #或者域名
这个目录是对的吗，ip一直访问不了
![image](https://user-images.githubusercontent.com/9979023/71902635-74f41080-319d-11ea-9540-50e5108adc42.png)

**Comment by timesons** [comment]
> server_name _; #或者域名

解决了，顺便反馈下，经测试临时域名不能访问，只能是固定域名。
