### ISSUE TITLE
登陆问题

### ISSUE THREAD

**Issue by saeson001** [master-coder-ll/v2ray-web-manager#20]
admin.properties设置如下

#email

#邮箱用户名
email.userName=saeson001@gmail.com
#密码
email.password=aaaaaaaa
#游戏smtp地址
email.host=smtp.gmail.com
#端口
email.port=465

#发送验证码模板
email.vCodeTemplate=你的验证码为: %s,请在10分钟内使用.
#和proxy端通讯的认证密码.
proxy.api.auth=42000004962020021

#admin 初始化生成的账号
admin.email=saeson001@gmail.com
admin.password=A123456a

proxy.properties设置如下
proxy.env=dev
#netty 监听端口
proxy.localPort=8081
proxy.maxConnections=300

#proxy访问认证密码
proxy.auth=42000004962020021
#admin 管理地址和端口，如果admin端也在本机不需要修改
manager.address=http://127.0.0.1:9091
#adminApi 地址端口改变这也需要修改
manager.getProxyAccountUrl=http://127.0.0.1:9091/proxy/proxyAccount/ac?accountNo={accountNo}
#adminApi 地址端口改变这也需要修改
manager.reportFlowUrl=http://127.0.0.1:9091/report/flowStat

server.tomcat.max-threads=2
server.tomcat.min-threads=1

logging.level.root=info
#logging.path=/opt/jar/logs/
logging.file=/opt/jar/logs/v2ray-proxy.log
logging.file.max-history=7
#proxy管理端口
server.port=8091

现在总是提示账号密码不对，注册账号能提示已发送验证码，邮箱没收到任何内容

**Comment by master-coder-ll** [comment]
1.  gmail邮箱需要开通smtp 很复杂。主要原因是：gmail 没开通权限。

2.  密码不对，你是否重新设置了密码了，比如：原密码是123456，然后你修改配置文件的密码为A123456? 这种情况在邮箱不能用的情况下，需要删除数据库文件 位于：/opt/jar/db/

**Comment by saeson001** [comment]
> 1. gmail邮箱需要开通smtp 很复杂。主要原因是：gmail 没开通权限。邮件是异步发送的，提供日志 /opt/jar/logs/admin.log
> 2. 密码不对，你是否重新设置了密码了，比如：原密码是123456，然后你修改配置文件的密码为A123456? 这种情况在邮箱不能用的情况下，需要删除数据库文件 位于：/opt/jar/db/

然后mkdir /opt/jar/db -p ?

**Comment by master-coder-ll** [comment]
> 然后mkdir /opt/jar/db -p ?
可以

**Comment by saeson001** [comment]
原来是删除数据库，再重建目录，上面就有个蓝色进度条一直在load卡着，
再删除数据库，重启JAVA就直接进去了，现在建立服务器时出现下面的提示

error performing isolated work; nested exception is org.hibernate.exception.GenericJDBCException: error performing isolated work

**Comment by goodjimli** [comment]
> 原来是删除数据库，再重建目录，上面就有个蓝色进度条一直在load卡着，
> 再删除数据库，重启JAVA就直接进去了，现在建立服务器时出现下面的提示
> 
> error performing isolated work; nested exception is org.hibernate.exception.GenericJDBCException: error performing isolated work

重试

**Comment by master-coder-ll** [comment]
> 原来是删除数据库，再重建目录，上面就有个蓝色进度条一直在load卡着，
> 再删除数据库，重启JAVA就直接进去了，现在建立服务器时出现下面的提示
> 
> error performing isolated work; nested exception is org.hibernate.exception.GenericJDBCException: error performing isolated work

重试

**Comment by master-coder-ll** [comment]
Duplicate of #21
