### ISSUE TITLE
数据库文件 admin.db 要用哪个编辑器编辑？

### ISSUE THREAD

**Issue by doutuo** [master-coder-ll/v2ray-web-manager#205]
数据库文件 admin.db 要用哪个编辑器编辑？
网上找了几个，打开不是乱码就是时间是错的，
我想修改数据库。
有大老用过吗

**Comment by master-coder-ll** [comment]
sqllite数据库， navicat 之类都可以

**Comment by doutuo** [comment]
[![gCR7d0.png](https://z3.ax1x.com/2021/04/27/gCR7d0.png)](https://imgtu.com/i/gCR7d0)
打开db 这个时间 怎么是这样子的，我是想要打开数据库修改结算时间。
现在咱们这套结算时间没法修改，只能修改有效时间
