### ISSUE TITLE
运行一段时间以后,用户第一次一直链接不成功,需要重新链接一次,才能用

### ISSUE THREAD

**Issue by ocswor** [master-coder-ll/v2ray-web-manager#208]
## 你的问题是什么？
运行一段时间以后,用户第一次一直链接不成功,需要重新链接一次,才能用

有人遇到和我一样的问题么?
有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤
暂时还没有复现问题,也没有明显的错误日志,日志看不太懂
## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
用户第一次链接,就可以直接用

**Comment by ocswor** [comment]
感觉不太稳定,经常连不上,需要重启一下才行 ,有和我遇到同样问题的么?

**Comment by master-coder-ll** [comment]
> 感觉不太稳定,经常连不上,需要重启一下才行 ,有和我遇到同样问题的么?
没发现
