### ISSUE TITLE
v2ray更新，现在alterid要改成0才能上网，麻烦作者更新下

### ISSUE THREAD

**Issue by doutuo** [master-coder-ll/v2ray-web-manager#218]
v2ray更新了，现在alterid要改成0才能上网，麻烦作者更新下
咱们的系统生成的vmess链接的配置，alterid默认还是64，改成0

**Comment by xinqiankb** [comment]
大佬，我改了0还是不行呢

**Comment by doutuo** [comment]
> 大佬，我改了0还是不行呢

去下载4.34版的，把服务器端降级，重启服务器后就可以了

**Comment by heyu988** [comment]
官方淘汰了 VMess MD5 认证信息机制

需要服务端修改文件 v2ray.service
# /etc/systemd/system/v2ray.service

文件中 [Service] 的下方增加 Environment="V2RAY_VMESS_AEAD_FORCED=false"  来强制使用VMess MD5 认证信息机制

这样alterID 为64 也可以继续使用

还是希望作者更新一下wmess链接的配置   官方说 VMess MD5 认证是有安全漏洞的

**Comment by master-coder-ll** [comment]
已更新

**Comment by WeiMXi** [comment]
> 已更新

我看作者的更新好像是[在安装教程中直接指定v2ray版本为4.33](https://github.com/master-coder-ll/v2ray-web-manager/commit/7348d32e175f0c773327d2bb8b2a288827057d29)，
但是我用的[路由器的插件，作为客户端也禁止了alter ID](https://github.com/fw876/helloworld/issues/758)不为零的链接，
作者可否更新一下程序，使得管理员可以自己配置服务端vmess的一些参数？

**Comment by WeiMXi** [comment]
@xinqiankb @heyu988 @doutuo @master-coder-ll 
我提交了一个pull request，尝试更改AlterID为0，但我不懂Java，也没细看代码，只是搜索`64`，`aid`，`alterid`等字符，然后更改为0，目前我自己编译了jar包，在正常使用，希望作者可以看看有没有问题，可不可以合并分支，如果比较急的话可以使用[我编译的版本](https://github.com/WeiMXi/v2ray-web-manager)

**Comment by minmudiao** [comment]
> 官方淘汰了 VMess MD5 认证信息机制
> 
> 需要服务端修改文件 v2ray.service
> 路径 ： /etc/systemd/system/v2ray.service
> 
> 文件中 [Service] 的下方增加 Environment="V2RAY_VMESS_AEAD_FORCED=false"  来强制使用VMess MD5 认证信息机制
> 
> 这样alterID 为64 也可以继续使用
> 
> 还是希望作者更新一下wmess链接的配置   官方说 VMess MD5 认证是有安全漏洞的
> 
>
