### ISSUE TITLE
#小白鼠

### ISSUE THREAD

**Issue by 1747874091** [master-coder-ll/v2ray-web-manager#23]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

**Comment by 1747874091** [comment]
还有 unzip dist.zip  -d web 这个 dist.zip下载可没有 ls查看只有dist  不知道是因为你粗心还是怎么的 
或者unzip dist  -d web

**Comment by master-coder-ll** [comment]
https://github.com/master-coder-ll/v2ray-web-manager/tree/master/conf

**Comment by master-coder-ll** [comment]
> 还有 unzip dist.zip -d web 这个 dist.zip下载可没有 ls查看只有dist 不知道是因为你粗心还是怎么的
> 或者unzip dist -d web

没有后缀？

**Comment by 1747874091** [comment]
> > 还有 unzip dist.zip -d web 这个 dist.zip下载可没有 ls查看只有dist 不知道是因为你粗心还是怎么的
> > 或者unzip dist -d web
> 
> 没有后缀？

对

**Comment by 1747874091** [comment]
对了 如果我需要配置tls在哪里可以设置呢

**Comment by 1747874091** [comment]
搭建完登录 提示Request failed with status code 502

**Comment by master-coder-ll** [comment]
> 搭建完登录 提示Request failed with status code 502

不能直接用浏览器访问

**Comment by 1747874091** [comment]
> > 搭建完登录 提示Request failed with status code 502
> 
> 不能直接用浏览器访问

哈 那怎么访问啊

**Comment by master-coder-ll** [comment]
> > 搭建完登录 提示Request failed with status code 502
> 
> 不能直接用浏览器访问

还是说访问admin端报

> > > 搭建完登录 提示Request failed with status code 502
> > 
> > 
> > 不能直接用浏览器访问
> 
> 哈 那怎么访问啊

Admin端报错？

**Comment by 1747874091** [comment]
> > > 搭建完登录 提示Request failed with status code 502
> > 
> > 
> > 不能直接用浏览器访问
> 
> 还是说访问admin端报
> 
> > > > 搭建完登录 提示Request failed with status code 502
> > > 
> > > 
> > > 不能直接用浏览器访问
> > 
> > 
> > 哈 那怎么访问啊
> 
> Admin端报错？

登录的时候提示  页面没有跳转

**Comment by master-coder-ll** [comment]
1.  java admin 服务没有起来， `ps -ef | grep java`

2.  如果起来 查看日志 /opt/jar/logs/admin.log

**Comment by 1747874091** [comment]
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://47.240.116.30/ws/h3cr0ml:87e8454f6e9aed89e00262557168fabf/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

客户端 报错 没有使用tls 和你图片里面的配置相同

**Comment by master-coder-ll** [comment]
> [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://47.240.116.30/ws/h3cr0ml:87e8454f6e9aed89e00262557168fabf/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
> 
> 客户端 报错 没有使用tls 和你图片里面的配置相同

看你这情况，是直连的v2ray，没有经过proxy端的转发。复制我的账号中生成的配置

**Comment by 1747874091** [comment]
> > [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://47.240.116.30/ws/h3cr0ml:87e8454f6e9aed89e00262557168fabf/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
> > 客户端 报错 没有使用tls 和你图片里面的配置相同
> 
> 看你这情况，是直连的v2ray，没有经过proxy端的转发。复制我的账号中生成的配置

我这个 是由订阅弄得

**Comment by 1747874091** [comment]
ws+tls目前还没有实现对吗

**Comment by 1747874091** [comment]
centos报错 nginx: [error] open() "/run/nginx.pid" failed (2: No such file or directory)

**Comment by 1747874091** [comment]
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)

ws报错部分

**Comment by 1747874091** [comment]
所以为什么没有 tcp的呢

**Comment by master-coder-ll** [comment]
> 所以为什么没有 tcp的呢

ws和http2 是未来的出路，其他不用想。

**Comment by 1747874091** [comment]
> > 所以为什么没有 tcp的呢
> 
> ws和http2 是未来的出路，其他不用想。

刚刚我测试了下proxy端 连接admin端 那个proxy 那个地址可以使用域名吗 我加了域名发现好像炸了 连接不上

**Comment by master-coder-ll** [comment]
> 刚刚我测试了下proxy端 连接admin端 那个proxy 那个地址可以使用域名吗 我加了域名发现好像炸了 连接不上

读支持域名连接

**Comment by 1747874091** [comment]
> > 刚刚我测试了下proxy端 连接admin端 那个proxy 那个地址可以使用域名吗 我加了域名发现好像炸了 连接不上
> 
> 都支持域名连接

访问端口就是NGINX的自己定义的端口咯？  不一定80 也可以吧？

**Comment by master-coder-ll** [comment]
> > > 刚刚我测试了下proxy端 连接admin端 那个proxy 那个地址可以使用域名吗 我加了域名发现好像炸了 连接不上
> > 
> > 
> > 都支持域名连接
> 
> 访问端口就是NGINX的自己定义的端口咯？ 不一定80 也可以吧？

proxy 连接admin端的地址 需要时解析出来的要是直连IP,如果不是需要自己配置nginx 转发

**Comment by 1747874091** [comment]
proxy端 可以单独安装proxy文件的吧 我感觉可以的

**Comment by master-coder-ll** [comment]
> proxy端 可以单独安装proxy文件的吧 我感觉可以的

可以。详情查看模式

**Comment by 1747874091** [comment]
> > proxy端 可以单独安装proxy文件的吧 我感觉可以的
> 
> 可以。详情查看模式

就很棒 我测试去了 
这个是centos报错 搭建 NGINX 的
nginx: [error] open() "/run/nginx.pid" failed (2: No such file or directory)

你处理看看

**Comment by master-coder-ll** [comment]
nginx 错误 Google 一下

**Comment by 1747874091** [comment]
> nginx 错误 Google 一下

肯定是谷歌过了 都有问题

**Comment by 1747874091** [comment]
> > 所以为什么没有 tcp的呢
> 
> ws和http2 是未来的出路，其他不用想。

ws用不了iptables 流量中转 不知道h2如何
