### ISSUE TITLE
为什么nginx状态码一直返回 101, 499 什么都无法访问

### ISSUE THREAD

**Issue by umrchen** [master-coder-ll/v2ray-web-manager#231]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

**Comment by umrchen** [comment]
java日志都正常
nginx
![image](https://user-images.githubusercontent.com/118820159/206866574-7fce8e16-9faa-4f98-bba0-26cc8ef54cbe.png)

**Comment by uimeet** [comment]
看一下 v2ray 的日志
