### ISSUE TITLE
修改管理界面生成默认alterId？管理员不能修改配置参数？新用户不会自动添加到v2ray的config.json？

### ISSUE THREAD

**Issue by lucas-yang256** [master-coder-ll/v2ray-web-manager#233]
管理界面发现三个问题：
说明：管理面板是按照readme当中的[step by step install](https://github.com/master-coder-ll/v2ray-web-manager/blob/master/step-by-step-install.md) 来操作的。
**问题1：**
如图，生成的默认alterId是64，如何改成默认是0 呢？我发现alterId=64的时候网速比较慢，所以想让生成的默认值为0，但是没找到修改的地方，请问如何让每次选择完服务器之后出来的alterId是0呢？
![image](https://user-images.githubusercontent.com/30977875/226156492-5db2ae04-5156-476e-958a-91f51d784dc1.png)

**问题2：**管理员无法修改用户配置参数？
如图，在管理员界面，没有看到可以修改用户配置参数的选项，比如上一个问题中如果管理员可以修改alterId，则会比较方便
![image](https://user-images.githubusercontent.com/30977875/226156590-89cdd8e6-337a-48f5-8c9a-013bef5f1834.png)
![image](https://user-images.githubusercontent.com/30977875/226156947-070782d2-d81f-4210-ac5e-54a7aa8c8ad8.png)

**问题3：** 在管理面板当中注册用户之后，新用户的id并不能自动添加到v2ray 的config.json文件当中去，中间是不是缺少了一个脚本，还是我配置有问题？有大佬了解吗？

**Comment by master-coder-ll** [comment]
fixed [https://github.com/master-coder-ll/v2ray-web-manager/releases/tag/v3.1.13](v3.1.13)
