### ISSUE TITLE
会员账号首次登录，跳转到了404页面

### ISSUE THREAD

**Issue by xifanu** [master-coder-ll/v2ray-web-manager#29]
## 问题现象

会员账号首次登录，跳转到了404页面。

## 出现问题的情况是怎么样的？

1. 使用管理员账号创建新会员用户
2. 退出管理员账号，使用新创建的会员用户登录
3. 登录成功，但跳转到了404页面。

**Comment by master-coder-ll** [comment]
基本没影响，只有管理员会这样 。原因退出登录携带redirect，因普通会员没权限，重定向到404页面
