### ISSUE TITLE
QoS 实现原理

### ISSUE THREAD

**Issue by billzhong** [master-coder-ll/v2ray-web-manager#3]
V2Ray 的 API 并没有实现速率控制啊。我看了安装教程，V2Ray 也是用的官方版本。请问如何做到 QoS 的呢？如果能告诉具体代码的位置更好。谢谢。

更新：我重新看了下构架图，是不是速率控制和流量统计部分，都由 Java 写的 http proxy 完成呢？如果这样的话，那没办法实现直接 vmess 连接吧。

**Comment by master-coder-ll** [comment]
Qos实现是用java 写的， proxy 项目。

proxy 是工作在传输层上，不必理会应用层的协议。包括vmess

具体代码 [TrafficController.java](https://github.com/master-coder-ll/v2ray-web-manager/blob/master/proxy/src/main/java/com/jhl/TrafficController/TrafficController.java)
和[HexDumpProxyFrontendHandler.java](https://github.com/master-coder-ll/v2ray-web-manager/blob/master/proxy/src/main/java/com/jhl/proxy/HexDumpProxyFrontendHandler.java)
