### ISSUE TITLE
流量超过限额后，http连接不能完全关闭

### ISSUE THREAD

**Issue by xifanu** [master-coder-ll/v2ray-web-manager#30]
## 你的问题是什么？

流量超过限额后，（客户端不主动断开连接）存在http连接不能完全关闭的情况，仍可联网；

## 出现问题的情况是怎么样的？

流量超过限额后，后台信息显示仍有一个未关闭的连接，此时可以访问网络

## 相关日志 java服务日志位于/opt/jar/logs
- 部分日志
> 阻止远程请求:hnl13mr
> 获取不到账号
> 关闭当前连接数后->account:hnl13mr:127.0.0.1,：2
> 关闭当前连接数后->account:hnl13mr:127.0.0.1,：1
> 当前连接数account:hnl13mr:127.0.0.1,2
> 阻止远程请求:hnl13mr
> 获取不到账号
> 关闭当前连接数后->account:hnl13mr:127.0.0.1,：1

**Comment by master-coder-ll** [comment]
问题不大。现在只对新建连接进行阻断，没有强制中断已经建立的连接。少量的超流量无关紧要。
