### ISSUE TITLE
java服务 jvm 优化

### ISSUE THREAD

**Issue by master-coder-ll** [master-coder-ll/v2ray-web-manager#33]
使用的是[openj9-jvm](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9) ,参数如下：

```bash
admin 端 
nohup java -jar  -Xmx40m -Xiss64k -Xss320k  -XcompilationThreads1 -XX:+UseCompressedOops -verbose:sizes -XX:MaxDirectMemorySize=10M -XX:MetaspaceSize=40M -XX:MaxMetaspaceSize=70m  -Xscmx60M -Xscmaxaot8M -Xquickstart /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1 &

proxy 端
nohup java -jar   -Xmx35m -Xiss64k -Xss320k -XcompilationThreads1 -XX:+UseCompressedOops -verbose:sizes -XX:MaxDirectMemorySize=10M  -XX:MaxMetaspaceSize=70m  -Xscmx60M -Xscmaxaot8M -Xquickstart /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml  > /dev/null 2>&1 &
```
以上优化都是基于j9-jvm，不适合openjdk8。如何服务访问量大，应适当按照各自情况来调整

**Comment by JohnGuan** [comment]
大佬有详细的替换教程和说明吗？

**Comment by jnsday** [comment]
JVM:
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9
cd /root/
wget https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u252-b09_openj9-0.20.0/OpenJDK8U-jre_x64_linux_openj9_8u252b09_openj9-0.20.0.tar.gz

tar -xvf OpenJDK8U-jre_x64_linux_openj9_8u252b09_openj9-0.20.0.tar.gz

vim .bash_profile
按方向键移动光标到最下面，然后按i键进入编辑模式：
添加
export JAVA_HOME=/root/jdk8u252-b09-jre
PATH=$PATH:$JAVA_HOME/bin

source .bash_profile

java -version
检查
