### ISSUE TITLE
运行一段时间后宕机

### ISSUE THREAD

**Issue by shenmirenQUQ** [master-coder-ll/v2ray-web-manager#38]
换了好几个配置了。
现在用1个cpu+1.7g内存。
搭建好后正常运行，
过了一段时间就死机了。连ssh都无法连接，只能强制重启。
就运行了这个项目，其他什么都没有。
是因为配置太低了吗？

**Comment by shenmirenQUQ** [comment]
系统是Ubuntu16.04，是否CentOS会好一点？
感谢

**Comment by master-coder-ll** [comment]
我都运行了半年有余，512M的内存都可以装的下2个java服务。
建议你重新安装，不清楚你声明情况。
是什么`进程`导致，相关日志？
java 服务远行越久越快

**Comment by shenmirenQUQ** [comment]
> 我都运行了半年有余，512M的内存都可以安装的下2个java服务。
> 建议您重新安装，清楚你声明情况。
> 是什么`进程`导致，相关日志？
> java服务远行越久越快

目前在安装CentOS重装中。想问下你用的什么系统？

**Comment by master-coder-ll** [comment]
> > 我都运行了半年有余，512M的内存都可以安装的下2个java服务。
> > 建议您重新安装，清楚你声明情况。
> > 是什么`进程`导致，相关日志？
> > java服务远行越久越快
> 
> 目前在安装CentOS重装中。想问下你用的什么系统？

Ubuntu

**Comment by shenmirenQUQ** [comment]
> > > 我都运行了半年有余，512M的内存都可以安装的下2个java服务。
> > > 建议您重新安装，清楚你声明情况。
> > > 是什么`进程`导致，相关日志？
> > > java服务远行越久越快
> > 
> > 
> > 目前在安装CentOS重装中。想问下你用的什么系统？
> 
> Ubuntu

这样 ，那有可能是我的问题了。
不过我每一步都是按照教程来的。好像没有错误的地方。
并且已经更改过几次配置了。

**Comment by master-coder-ll** [comment]
修改配置后需要`关闭`原来的 Java服务，在重新启动

**Comment by shenmirenQUQ** [comment]
> 修改配置后需要`关闭`原来的Java服务，在重新启动

配置好了，我没有修改任何配置。只是添加了用户。

新建的用户默认的流量和连接数速率这些能修改吗？
建议下一版加上速率，流量留空是无限的选项。
