### ISSUE TITLE
关于服务器设置问题相关

### ISSUE THREAD

**Issue by timesons** [master-coder-ll/v2ray-web-manager#4]
v2ray-web-manager面板搭建完毕，访问正常，现遇到如下问题：
1：面板是否自带v2ray sever服务？（意思是服务器配置填面板ip或域名行不行）
2:  v2rayTag 是什么？需要填什么
![image](https://user-images.githubusercontent.com/9979023/71908676-6f042c80-31a9-11ea-9dd5-db844a981908.png)
3: 服务器配置》访问域名这里只能是域名吗，ip可不可以？
![image](https://user-images.githubusercontent.com/9979023/71908869-c3a7a780-31a9-11ea-921b-ac6c1d3d2564.png)

**Comment by timesons** [comment]
1，服务器信息更新后，账号管理》v2ray账号信息未同步
2，注册用户，v2ray账号信息也未同步，即使重新选择服务器也不行

**Comment by timesons** [comment]
登陆经常发生错误  timeout of 5000ms exceeded 
![image](https://user-images.githubusercontent.com/9979023/71918763-f2c81400-31bd-11ea-8ad1-222e8a662006.png)

**Comment by master-coder-ll** [comment]
1.  几种模式的配置，待我写个文档

2.  服务器更新没同步V2ray账号，设计之时：服务器并不是轻易改变的，并且也是一种延迟加载的思想

3. 重新选择相同的服务器 不会更新v2ray账号

4. 网络问题超时

**Comment by master-coder-ll** [comment]
下次更新，选择相同的服务器，重新生成v2ray账号

**Comment by master-coder-ll** [comment]
https://github.com/master-coder-ll/v2ray-web-manager/blob/master/step-by-step-model.md
