### ISSUE TITLE
一系列问题如下

### ISSUE THREAD

**Issue by iamlinhui** [master-coder-ll/v2ray-web-manager#40]
## 你的问题是什么？

1. 调用client添加和删除账号的时候  会抛出这个异常信息
ERROR 15794 --- [nioEventLoopGroup-3-2] com.jhl.v2ray.service.V2rayService       : addProxyAccount error:UNKNOWN: v2ray.com/core/proxy/vmess/inbound: User ******@qq.com already exists.,

2. 手动触发垃圾回收可能会抛出这个异常
ERROR 15794 --- [nioEventLoopGroup-3-1] io.netty.util.ResourceLeakDetector       : LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
        io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
        io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        java.lang.Thread.run(Thread.java:748)

3. 当用户周期内流量达到上限的时候，居然还能继续连接使用
    当冻结禁止账户的时候，居然还能继续连接使用

4.账户页面报错问题
Msg: Cannot read property 'desc' of null
Info: vue-component-88-UserAccount error in render
Url: https://*******/#/account/VipAccount

TypeError: Cannot read property 'desc' of null at a.r (https://*****/static/js/chunk-080e4529.2d73bf96.js:1:6729) at a.t._render (https://*****/static/js/chunk-libs.a6396719.js:18:23733) at a.r (https://*****/static/js/chunk-libs.a6396719.js:18:27824) at nr.get (https://*****/static/js/chunk-libs.a6396719.js:18:30684) at nr.run (https://*****/static/js/chunk-libs.a6396719.js:18:31417) at Jn (https://*****/static/js/chunk-libs.a6396719.js:18:29624) at Array.<anonymous> (https://*****/static/js/chunk-libs.a6396719.js:18:12761) at ue (https://*****/static/js/chunk-libs.a6396719.js:18:12156)

**Comment by master-coder-ll** [comment]
1. 有幂等控制，不影响。

 2. 已经说得很明显，ByteBuf.release() was not called before it's garbage-collected，不要手动GC

 3. 升级版本。

 4. 账户页面报错问题，Cannot read property 'desc' of null  待解决。

**Comment by iamlinhui** [comment]
按照现在的架构 admin是可以管理多个proxy的，但是看到admin里面的
com.jhl.admin.model.Server#getProxyIp这里，如果是分机部署 这个请求是到不了proxy的，
而且后续能支持proxy对不同的用户开放么  还有不同的proxy和admin之间的authPassword能分别配置么

**Comment by master-coder-ll** [comment]
更新版本
