### ISSUE TITLE
是否打算支持mysql

### ISSUE THREAD

**Issue by lokisama** [master-coder-ll/v2ray-web-manager#44]
## 你的问题是什么？

大神你的代码未来是否打算支持mysql

## 出现问题的情况是怎么样的？

想放云mysql上去管理

## 相关日志 java服务日志位于/opt/jar/logs

无

## 期望结果？
jdbc配置改一下就好

**Comment by master-coder-ll** [comment]
支持所有关系型数据库；会的很简单，不会的也挺难的。不打算维护另外一个数据库

**Comment by lokisama** [comment]
ok，那我有空自己写然后pr，谢谢作者
