### ISSUE TITLE
admin设置速率不生效

### ISSUE THREAD

**Issue by simonliu9527** [master-coder-ll/v2ray-web-manager#48]
<img width="484" alt="ll" src="https://user-images.githubusercontent.com/55828739/76815878-cd98f700-6839-11ea-96ee-7f68b177aae4.png">
<img width="422" alt="ytb" src="https://user-images.githubusercontent.com/55828739/76815940-ef927980-6839-11ea-9c02-2bf5a7a16dd5.png">

大佬，我在admin设置限制用户速度设置的数字是1，但是不生效，youtube速度统计还能到几千KB。

**Comment by master-coder-ll** [comment]
是否是最新版？

**Comment by simonliu9527** [comment]
wget -c https://glare.now.sh/master-coder-ll/v2ray-web-manager/admin -O admin.jar
wget -c https://glare.now.sh/master-coder-ll/v2ray-manager-console/dist -O dist.zip
wget -c https://glare.now.sh/master-coder-ll/v2ray-web-manager/v2ray-proxy -O v2ray-proxy.jar

抱歉，我使用这种方式下载的，jar的名字丢失了版本了，有其他方式看版本吗？

**Comment by simonliu9527** [comment]
【proxy】
Manifest-Version: 1.0
Created-By: Apache Maven 3.6.0
Built-By: Administrator
Build-Jdk: 13.0.2
Implementation-Title: v2ray-proxy
Implementation-Version: 3.1.2
Implementation-Vendor-Id: com.jhl
Implementation-URL: https://projects.spring.io/spring-boot/#/spring-boot
 -starter-parent/v2ray-proxy
Main-Class: org.springframework.boot.loader.JarLauncher
Start-Class: com.jhl.V2rayProxyApplication
Spring-Boot-Version: 2.1.3.RELEASE
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/

【admin】
Manifest-Version: 1.0
Implementation-Title: vpn-admin
Implementation-Version: 3.1.1
Built-By: Administrator
Implementation-Vendor-Id: com.jhl
Spring-Boot-Version: 2.1.2.RELEASE
Main-Class: org.springframework.boot.loader.JarLauncher
Start-Class: com.jhl.admin.AdminApplication
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
Created-By: Apache Maven 3.6.0
Build-Jdk: 1.8.0_232
Implementation-URL: https://projects.spring.io/spring-boot/#/spring-bo
 ot-starter-parent/admin

**Comment by master-coder-ll** [comment]
> 是否是最新版？

**Comment by simonliu9527** [comment]
我将admin，proxy，web前端都重新部署了最新版了，一样会有限制不了的问题。

这个是我开v2ray的时候的测速结果：
<img width="563" alt="spt_jp" src="https://user-images.githubusercontent.com/55828739/76918708-ee2c8400-6901-11ea-91aa-74a298095777.png">

这个是不开v2ray的时候：
<img width="521" alt="spt_gz" src="https://user-images.githubusercontent.com/55828739/76918728-fd133680-6901-11ea-934c-56bb69886835.png">

admin设置：
<img width="460" alt="adminset" src="https://user-images.githubusercontent.com/55828739/76918912-5a0eec80-6902-11ea-8849-434949d1e558.png">

**Comment by matthuo333** [comment]
> 我将admin，proxy，web前端都重新部署了最新版了，一样会有限制不了的问题。
> 
> 这个是我开v2ray的时候的测速结果：
> <img alt="spt_jp" width="563" src="https://user-images.githubusercontent.com/55828739/76918708-ee2c8400-6901-11ea-91aa-74a298095777.png">
> 
> 这个是不开v2ray的时候：
> <img alt="spt_gz" width="521" src="https://user-images.githubusercontent.com/55828739/76918728-fd133680-6901-11ea-934c-56bb69886835.png">
> 
> admin设置：
> <img alt="adminset" width="460" src="https://user-images.githubusercontent.com/55828739/76918912-5a0eec80-6902-11ea-8849-434949d1e558.png">

最后Fix 了么？

**Comment by lawrence1751** [comment]
同樣遇到問題，速率第一次設定會生效，但是修改後就不會跟著更新速率調整，希望下一版能夠修正

**Comment by matthuo333** [comment]
貌似发现重点：
每次在面板设定速率后，必须对V2RAY-PROXY 进行重启，方能生效。 
当然这个需要请大神确认了

**Comment by matthuo333** [comment]
BTW， 对于流量监视，貌似一定时间就停止统计，需要重启下admin java进程。 这个能有什么机制，能定时查询么？
