### ISSUE TITLE
请问账号管理的连接数是指什么？

### ISSUE THREAD

**Issue by NathanWu12** [master-coder-ll/v2ray-web-manager#50]
本人用一台设备通过小火箭连接服务器后，看到后台日志连接数接近20，似乎不是我理解的限制用户连接服务器的设备。请问账号管理的连接数是指什么？如果是为了限制单个用户可以连接服务器的设备数又该怎么设置呢？

**Comment by master-coder-ll** [comment]
文件有说明

**Comment by matthuo333** [comment]
> 文件有说明
麻烦告知是在那个路径下么？没找到
