### ISSUE TITLE
关于通过订阅制度突破账号连接数限制的问题

### ISSUE THREAD

**Issue by NathanWu12** [master-coder-ll/v2ray-web-manager#52]
## 你的问题是什么？

在admin端设置了账号的连接限制，例如30。该账号使用订阅链接订阅了多台服务器，经过测试发现同一个订阅地址可以分别连接不同的服务器。由于连接限制是在各个服务端的proxy端进行管理的，只要用一个账号在不同设备连接不同的服务器，似乎就突破了单个账号连接数的限制。经过测试限制30连接数的账号可以在两台服务器上达到超过40个连接数。

## 期望结果？

请问实际情况是这样吗？还是我个人服务器设置有问题？如果确实是这样的话好像限制不了账号被共享的问题。

**Comment by master-coder-ll** [comment]
今天更新的弱一致性的全局控制，现在还是per release版本。你可以更新试试

**Comment by NathanWu12** [comment]
> 今天更新的弱一致性的全局控制，现在还是per release版本。你可以更新试试

谢谢您的工作。
我更新后，测试发现proxy端的服务器没有受到admin端的连接数限制，而是使用了默认的数值32。例如我在admin端服务器A设置了20的连接数限制，但在proxy端服务器B的log里显示的连接可以超过20，在达到32后才被限制。

**Comment by NathanWu12** [comment]
感谢大佬的工作。V3.1.4 在Proxy端成功受到Admin端连接数限制。

**Comment by matthuo333** [comment]
> 感谢大佬的工作。V3.1.4 在Proxy端成功受到Admin端连接数限制。

麻烦问下，这个版本号是在哪里查看？
