### ISSUE TITLE
设置相同域名的服务器问题

### ISSUE THREAD

**Issue by savaza** [master-coder-ll/v2ray-web-manager#56]
我目前用一台V2ray做中转服务，inbound6080端口outbound到日本VPS，现在我想再添加一个inbound6081端口outbound到北美VPS，当前版本不能保存相同域名的服务器，所以只能增加一个域名解析才能配置成功。

目前方案是：
NGINX将 jp.abc.com/ws 请求转发给proxy console，判断是服务器1转发到 v2ray的inbound6080 --> outbound日本VPS
NGINX将 us.abc.com/ws 请求转发给proxy console，判断是服务器2转发到 v2ray的inbound6081 --> outbound北美VPS

能否支持一个域名创建多个服务器，通过path区分服务器，从而转发给V2ray不同端口，比如：
nginx将 proxy.abc.com/wsjp 请求转发给 v2ray的inbound 6080
将proxy.abc.com/wsus 请求转发给 v2ray的inbound 6081

![image](https://user-images.githubusercontent.com/36786253/77430858-ce6ff100-6e16-11ea-9027-d9a8441b7a60.png)

**Comment by master-coder-ll** [comment]
那么为什么不创建多一个二级域名？

**Comment by savaza** [comment]
> 那么为什么不创建多一个二级域名？

现在是通过创建多个域名来解决的，不过这样需要增加相应的DNS解析，没有泛域名证书的同学需要申请多个单域名SSL证书。
我的需求通过多个域名已经解决了，如果不考虑增加这个功能，请关闭issue吧。
