### ISSUE TITLE
SMTP的设置问题，似乎无法发出邮件，我在DNS增加了MX记录，想请教一下具体怎么设置；另外就是请求超时的问题"timeout of 5000ms exceeded"，我找不到相应的js文件

### ISSUE THREAD

**Issue by luwa1107** [master-coder-ll/v2ray-web-manager#57]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

**Comment by luwa1107** [comment]
MTP的设置问题，似乎无法发出邮件，我在DNS增加了MX记录，想请教一下具体怎么设置 SMTP的设置问题，似乎无法发出邮件，我在DNS增加了MX记录，想请教一下具体怎么设置；另外就是请求超时的问题"timeout of 5000ms exceeded"，我找不到相应的js文件

**Comment by master-coder-ll** [comment]
1. 确保你能通过SMTP发送邮件
2. 开启startTlsEnabled 试试
3. 使用第三方SMTP服务

**Comment by master-coder-ll** [comment]
送你一句话，爱用不用，别bb。
没能力，没技术就不要搞花的。
`timeout of 5000ms exceeded `看不懂可以拿去翻译。
还有有能力你自己改，装什么
