### ISSUE TITLE
Discussions | 讨论区

### ISSUE THREAD

**Issue by master-coder-ll** [master-coder-ll/v2ray-web-manager#58]
Any ideas and suggestions？
你有什么想法和建议？

**Comment by luwa1107** [comment]
项目很不错，就是很容易出BUG，希望大佬能完善一下项目！

**Comment by master-coder-ll** [comment]
> 项目很不错，就是很容易出BUG，希望大佬能完善一下项目！

？？？，有bug就提，并且给出步骤，给出相应日志。别搞事情好不？

**Comment by master-coder-ll** [comment]
> 项目很不错，就是很容易出BUG，希望大佬能完善一下项目！

看你就是什么也不懂，一键安装的适合你。

**Comment by GODDOG-1** [comment]
尝试搭建后，速度比直接用233blog的一键脚本搭建的v2ray慢了十倍不止，请问这是为什么呢？

**Comment by master-coder-ll** [comment]
> 尝试搭建后，速度比直接用233blog的一键脚本搭建的v2ray慢了十倍不止，请问这是为什么呢？

 限速配置多少？连接数配置多少？什么时间段测试的？测试方式（全局spedtest）？

能搞明白上面的问题，你就不会这么说了

**Comment by Juancollado2003** [comment]
Ip counting in order to allow only certain ip's, something like Poseidon Collette

**Comment by master-coder-ll** [comment]
what

> Ip counting in order to allow only certain ip's, something like Poseidon Collette

What's Poseidon Collette?

**Comment by Juancollado2003** [comment]
> > Ip counting in order to allow only certain ip's, something like Poseidon Collette
> 
> Project has no IP counter, Are you talking about conenct counter?
> and What's Poseidon Collette?

https://github.com/ColetteContreras/v2ray-poseidon

Ip counting is the log of the ip is connecting with the v2ray profile, so you can see how many ip's are using the same profile simultaneously, poseidon give the option to limit the number of ip's connected to the same v2ray profile

**Comment by master-coder-ll** [comment]
> > > Ip counting in order to allow only certain ip's, something like Poseidon Collette
> > 
> > 
> > Project has no IP counter, Are you talking about conenct counter?
> > and What's Poseidon Collette?
> 
> https://github.com/ColetteContreras/v2ray-poseidon
> 
> Ip counting is the log of the ip is connecting with the v2ray profile, so you can see how many ip's are using the same profile simultaneously, poseidon give the option to limit the number of ip's connected to the same v2ray profile

sorry，> > > Ip counting in order to allow only certain ip's, something like Poseidon Collette
> > 
> > 
> > Project has no IP counter, Are you talking about conenct counter?
> > and What's Poseidon Collette?
> 
> https://github.com/ColetteContreras/v2ray-poseidon
> 
> Ip counting is the log of the ip is connecting with the v2ray profile, so you can see how many ip's are using the same profile simultaneously, poseidon give the option to limit the number of ip's connected to the same v2ray profile

sorry，it does not support v2ray-poseidon
