### ISSUE TITLE
登陆时出现 status erro 502

### ISSUE THREAD

**Issue by GeorgeChen0821** [master-coder-ll/v2ray-web-manager#59]

**Comment by master-coder-ll** [comment]
admin端没起来，或者异常

**Comment by GeorgeChen0821** [comment]
> admin端没起来，或者异常

不好意思 ，怎样可以排查异常，或者让admin启动呢，谢谢！！

**Comment by master-coder-ll** [comment]
> > admin端没起来，或者异常
> > 是每次重启完服务器 再登录就出现这个502了
> > 不好意思 ，怎样可以排查异常，或者让admin启动呢，谢谢！！

重启服务，你没启动java 服务，出现502 不正常吗？上不网不正常吗？

**Comment by GeorgeChen0821** [comment]
> > > admin端没起来，或者异常
> > > 是每次重启完服务器 再登录就出现这个502了
> > > 不好意思 ，怎样可以排查异常，或者让admin启动呢，谢谢！！
> 
> 重启服务，你没启动java 服务，出现502 不正常吗？上不网不正常吗？

谢谢！

**Comment by doutuo** [comment]
是的，这个admin proxy这两个java服务，需要手动重启，我设定了开机启动这两个服务，有时候能成功启动，有时候不行，很困惑。大神，能不能设定开机自动启动这两个服务呢？

**Comment by doutuo** [comment]
我是通过脚本 添加开机启动 centos7.6的， chkconfig 添加开机启动。但重启后，偶尔可以成功启动。十有八九是重启服务器后，不能自动启动admin服务或启动了服务，但登陆还是502，必须强制结束掉这两个进程，再手动启动admin 和  proxy服务才可以正常使用，有时候还得重复几次操作，才可成功。

**Comment by master-coder-ll** [comment]
> 我是通过脚本 添加开机启动 centos7.6的， chkconfig 添加开机启动。但重启后，偶尔可以成功启动。十有八九是重启服务器后，不能自动启动admin服务或启动了服务，但登陆还是502，必须强制结束掉这两个进程，再手动启动admin 和 proxy服务才可以正常使用，有时候还得重复几次操作，才可成功。

```bash
#!/bin/sh
#chkconfig: 2345 80 90
#description:开机自动启动的脚本程序
 
# 以下是脚本内容（自己根据需要进行编写）
# 启动一个Java示例程序
nohup java -jar /opt/java/hello-demo.jar &
```
#chkconfig: 2345 80 90  表示在2/3/4/5运行级别启动，启动序号(S80)，关闭序号(K90)；

```bash
chmod +x autostart.sh
chkconfig --add autostart.sh
chkconfig autostart.sh on
```

**Comment by doutuo** [comment]
> > 我是通过脚本 添加开机启动 centos7.6的， chkconfig 添加开机启动。但重启后，偶尔可以成功启动。十有八九是重启服务器后，不能自动启动admin服务或启动了服务，但登陆还是502，必须强制结束掉这两个进程，再手动启动admin 和 proxy服务才可以正常使用，有时候还得重复几次操作，才可成功。
> 
> ```shell
> cd /etc/rc.d/init.d/
> 
> #!/bin/sh
> #chkconfig: 2345 80 90
> #description:开机自动启动的脚本程序
>  
> # 以下是脚本内容（自己根据需要进行编写）
> # 启动一个Java示例程序
> nohup java -jar /opt/java/hello-demo.jar &
> ```
> 
> #chkconfig: 2345 80 90 表示在2/3/4/5运行级别启动，启动序号(S80)，关闭序号(K90)；
> 
> ```shell
> chmod +x autostart.sh
> chkconfig --add autostart.sh
> chkconfig autostart.sh on
> ```

请教下，开机自启脚本，我要启动admin  proxy 照下面写是否正确
-------
#!/bin/sh
#chkconfig: 2345 80 90
#description:开机自动启动的脚本程序
 
# 以下是脚本内容（自己根据需要进行编写）
# 启动一个Java示例程序
nohup java -jar /opt/java/admin.jar &
nohup java -jar /opt/java/v2ray-proxy.jar &

**Comment by doutuo** [comment]
这下面是我先前写的开机自启脚本，但启动十有八九不行，服务可能启动了，但登陆不上或502，我只能强制结束，再手动开启服务。
-------------
#!/bin/bash
# chkconfig: 2345 55 25
# description: jar
nohup java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m  /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1 &
nohup java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &

**Comment by savaza** [comment]
**Create v2panel-start.sh**
`vi /opt/jar/v2panel-start.sh`

> #!/bin/sh
> nohup java -jar -Xms256m -Xmx512m -XX:MaxDirectMemorySize=64M -XX:MaxMetaspaceSize=128m  /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1 &
> echo $! > /var/run/v2ray-admin.pid
> nohup java -jar -Xms256m -Xmx512m -XX:MaxDirectMemorySize=64M -XX:MaxMetaspaceSize=128m /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &
> echo $! > /var/run/v2ray-proxy.pid

**Create v2panel-stop.sh**
`vi /opt/jar/v2panel-stop.sh`
> #!/bin/sh
> PID1=${cat /var/run/v2ray-admin.pid}
> kill -15 $PID1
> PID2=${cat /var/run/v2ray-proxy.pid}
> kill -15 $PID2

**Register v2panel service**
`vi /etc/systemd/system/v2panel.service`

> [Unit]
> Description=v2ray-web-manager
> After=network.target network-online.target nss-lookup.target mysql.service mariadb.service mysqld.service
> [Service]
> Type=forking
> StandardError=journal
> ExecStart=/opt/jar/v2panel-start.sh
> ExecStop=/opt/jar/v2panel-stop.sh
> [Install]
> WantedBy=multi-user.target


**Set autostart**
`systemctl enable v2panel`
**Start service**
`systemctl start v2panel`
**Stop service**
`systemctl stop v2panel`

**Comment by master-coder-ll** [comment]
> **Create v2panel-start.sh**
> `vi /opt/jar/v2panel-start.sh`
> 
> > #!/bin/sh
> > nohup java -jar -Xms256m -Xmx512m -XX:MaxDirectMemorySize=64M -XX:MaxMetaspaceSize=128m  /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1 &
> > echo $! > /var/run/v2ray-admin.pid
> > nohup java -jar -Xms256m -Xmx512m -XX:MaxDirectMemorySize=64M -XX:MaxMetaspaceSize=128m /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &
> > echo $! > /var/run/v2ray-proxy.pid
> 
> **Create v2panel-stop.sh**
> `vi /opt/jar/v2panel-stop.sh`
> 
> > #!/bin/sh
> > PID1=${cat /var/run/v2ray-admin.pid}
> > kill -15 $PID1
> > PID2=${cat /var/run/v2ray-proxy.pid}
> > kill -15 $PID2
> 
> **Register v2panel service**
> `vi /etc/systemd/system/v2panel.service`
> 
> > [Unit]
> > Description=v2ray-web-manager
> > After=network.target network-online.target nss-lookup.target mysql.service mariadb.service mysqld.service
> > [Service]
> > Type=forking
> > StandardError=journal
> > ExecStart=/opt/jar/v2panel-start.sh
> > ExecStop=/opt/jar/v2panel-stop.sh
> > [Install]
> > WantedBy=multi-user.target
> 
> **Set autostart**
> `systemctl enable v2panel`
> **Start service**
> `systemctl start v2panel`
> **Stop service**
> `systemctl stop v2panel`

建议不要设置过高的堆。当然有这资源你可以随意

**Comment by doutuo** [comment]
> **Create v2panel-start.sh**
> `vi /opt/jar/v2panel-start.sh`
> 
> > #!/bin/sh
> > nohup java -jar -Xms256m -Xmx512m -XX:MaxDirectMemorySize=64M -XX:MaxMetaspaceSize=128m  /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1 &
> > echo $! > /var/run/v2ray-admin.pid
> > nohup java -jar -Xms256m -Xmx512m -XX:MaxDirectMemorySize=64M -XX:MaxMetaspaceSize=128m /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &
> > echo $! > /var/run/v2ray-proxy.pid
> 
> **Create v2panel-stop.sh**
> `vi /opt/jar/v2panel-stop.sh`
> 
> > #!/bin/sh
> > PID1=${cat /var/run/v2ray-admin.pid}
> > kill -15 $PID1
> > PID2=${cat /var/run/v2ray-proxy.pid}
> > kill -15 $PID2
> 
> **Register v2panel service**
> `vi /etc/systemd/system/v2panel.service`
> 
> > [Unit]
> > Description=v2ray-web-manager
> > After=network.target network-online.target nss-lookup.target mysql.service mariadb.service mysqld.service
> > [Service]
> > Type=forking
> > StandardError=journal
> > ExecStart=/opt/jar/v2panel-start.sh
> > ExecStop=/opt/jar/v2panel-stop.sh
> > [Install]
> > WantedBy=multi-user.target
> 
> **Set autostart**
> `systemctl enable v2panel`
> **Start service**
> `systemctl start v2panel`
> **Stop service**
> `systemctl stop v2panel`

厉害了，兄弟，谢谢分享！
