### ISSUE TITLE
收集各种建议、需求

### ISSUE THREAD

**Issue by master-coder-ll** [master-coder-ll/v2ray-web-manager#6]
收集各种建议、需求

**对于支付类的需求不做**

**Comment by kokasou** [comment]
可以在用戶管理裡面添加用戶備註嗎？只有email地址的話都不知道誰跟誰。感謝

**Comment by master-coder-ll** [comment]
> 可以在用戶管理裡面添加用戶備註嗎？只有email地址的話都不知道誰跟誰。感

> 可以在用戶管理裡面添加用戶備註嗎？只有email地址的話都不知道誰跟誰。感謝

// to do

**Comment by awds888** [comment]
可否提供方便的订阅管理功能，不同节点可以联动这类需求，其中一个作为经理，其余节点分店这种模式。

**Comment by master-coder-ll** [comment]
> 可否提供方便的订阅管理功能，不同节点可以联动这类需求，其中一个作为经理，其余节点分店这种模式。

1.不同的客户端好像订阅实现都不同，没统一的标准。
2.现在就是这种模型

**Comment by master-coder-ll** [comment]
> 可否提供方便的订阅管理功能，不同节点可以联动这类需求，其中一个作为经理，其余节点分店这种模式。

订阅需要进一步研究

**Comment by IrrationalSword** [comment]
如果端口不是80的话新建的服务器就连接不上是为什么呢？
将用户删除之后原有的连接依然可以使用，该怎么删除呢？
感谢大佬

**Comment by master-coder-ll** [comment]
> 如果端口不是80的话新建的服务器就连接不上是为什么呢？
> 将用户删除之后原有的连接依然可以使用，该怎么删除呢？
> 感谢大佬

重新下载最新的release包。v2.3以上已经修复

有缓存，计划v2.4以上版本增加删除同步到proxy端

**Comment by awds888** [comment]
能不能同步把自动证书管理做了，我是小白，我懒。另外安装过程好像没有针对centos的操作，有一键脚本最好。

**Comment by simonliu9527** [comment]
1.能加上限制用户ip和设备数的功能吗。2.可以加上单节点服务器使用流量统计和单个用户使用流量统计。可以按小时，天，月查询等。另外，大佬，有没有电报组或者其他可以直接沟通的地方，提issue方式不够直接。
