### ISSUE TITLE
关于全局连接数的一些理论

### ISSUE THREAD

**Issue by master-coder-ll** [master-coder-ll/v2ray-web-manager#60]
在分布式系统中，有两套理论`CAP`和`BASE`理论。

在当前设计和编码全局连接数控制的时候，也是遵循这2套理论而来。

在需要保证性能和容错性的前提下，`P` 确定,C（一致性）和A（可用性）是一种互斥的关系。

在当前的环境中，很多是跨机房，跨国家 进行部署的，延迟基本都是`200ms以上`，如需要保证C（一致性），那么会极大（90%）的降低proxy端的性能，所有`保证一致性(C)是不可取的`。

所以，当前的实现是基于AP模型。

对与C（一致性）的保证上，基于BASE理论来实现，在无法实现强一致性的情况下，`全局连接数` 可以有中间态（一定时间内的脏数据），但是最终会到达最终一致性。

这就是为什么，全局连接数看起来不准确的原因。

**Comment by matthuo333** [comment]
> 在分布式系统中，有两套理论`CAP`和`BASE`理论。
> 
> 在当前设计和编码全局连接数控制的时候，也是遵循这2套理论而来。
> 
> 在需要保证性能和容错性的前提下，`P` 确定,C（一致性）和A（可用性）是一种互斥的关系。
> 
> 在当前的环境中，很多是跨机房，跨国家 进行部署的，延迟基本都是`200ms以上`，如需要保证C（一致性），那么会极大（90%）的降低proxy端的性能，所有`保证一致性(C)是不可取的`。
> 
> 所以，当前的实现是基于AP模型。
> 
> 对与C（一致性）的保证上，基于BASE理论来实现，在无法实现强一致性的情况下，`全局连接数` 可以有中间态（一定时间内的脏数据），但是最终会到达最终一致性。
> 
> 这就是为什么，全局连接数看起来不准确的原因。

所以针对每个账号设定连接数的原则是？貌似和限速有一定的配比关系？
