### ISSUE TITLE
管理脚本参考

### ISSUE THREAD

**Issue by master-coder-ll** [master-coder-ll/v2ray-web-manager#62]
**Create v2panel-start.sh**
`vi /opt/jar/v2panel-start.sh`

> #!/bin/sh
> nohup java -jar  -Xmx40m -XX:MaxDirectMemorySize=8M -XX:MaxMetaspaceSize=80m  /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1 &
> echo $! > /var/run/v2ray-admin.pid
> nohup java -jar -Xmx40m -XX:MaxDirectMemorySize=8M -XX:MaxMetaspaceSize=48m /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &
> echo $! > /var/run/v2ray-proxy.pid

**Create v2panel-stop.sh**
`vi /opt/jar/v2panel-stop.sh`
> #!/bin/sh
> PID1=${cat /var/run/v2ray-admin.pid}
> kill -15 $PID1
> PID2=${cat /var/run/v2ray-proxy.pid}
> kill -15 $PID2

**Register v2panel service**
`vi /etc/systemd/system/v2panel.service`

> [Unit]
> Description=v2ray-web-manager
> After=network.target network-online.target nss-lookup.target mysql.service mariadb.service mysqld.service
> [Service]
> Type=forking
> StandardError=journal
> ExecStart=/opt/jar/v2panel-start.sh
> ExecStop=/opt/jar/v2panel-stop.sh
> [Install]
> WantedBy=multi-user.target

**Set autostart**
`systemctl enable v2panel`
**Start service**
`systemctl start v2panel`
**Stop service**
`systemctl stop v2panel`

_Originally posted by @savaza in https://github.com/master-coder-ll/v2ray-web-manager/issues/59#issuecomment-605067523_

**Comment by master-coder-ll** [comment]
建议相关`启动参数`按照教程中设置，如何你的主机很多内存，当我没说
```bash
nohup java -jar -Xms256m -Xmx512m -XX:MaxDirectMemorySize=64M -XX:MaxMetaspaceSize=128m /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1 &

nohup java -jar -Xms256m -Xmx512m -XX:MaxDirectMemorySize=64M -XX:MaxMetaspaceSize=128m /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &
```

**Comment by latorc** [comment]
java 小白提问：
有几次启动时，java提示 Exception out of memory
是否有必要提高内存/堆分配。

**Comment by lawrence1751** [comment]
針對Linux作業系統比較不熟悉的朋友

在設定開機自動啟動v2proxy的時候有發現腳本在各系統架構的有些許不太一樣的語法格式
使用Ubuntu的朋友如果單一執行腳本出現Bad Substitution，請把"{"、"}"改成"("、")"即可

Ubuntu: 
**Create v2panel-stop.sh**

```
#!/bin/sh
PID1=$(cat /var/run/v2ray-admin.pid)
kill -15 $PID1
PID2=$(cat /var/run/v2ray-proxy.pid)
kill -15 $PID2
```

腳本記得檢查是否有無執行權限，若無執行權限會無法順利執行v2panel.service

**Comment by climba03003** [comment]
直接使用 `systemctl` 管理進程

`vi /etc/systemd/system/v2ray-admin.service`

```
[Unit]
Description=V2Ray Admin
After=network.target

[Service]
SuccessExitStatus=143
User=root
Group=root
Type=simple
WorkingDirectory=/opt/jar
ExecStart=/usr/bin/java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m admin.jar --spring.config.location=/opt/jar/admin.yaml
ExecStop=/bin/kill -15 $MAINPID

[Install]
WantedBy=multi-user.target
```

`vi /etc/systemd/system/v2ray-proxy.service`

```
[Unit]
Description=V2Ray Proxy
After=network.target

[Service]
SuccessExitStatus=143
User=root
Group=root
Type=simple
WorkingDirectory=/opt/jar
ExecStart=/usr/bin/java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml
ExecStop=/bin/kill -15 $MAINPID

[Install]
WantedBy=multi-user.target
```
