### ISSUE TITLE
试了好多次不成功，可否制作一键安装脚本？

### ISSUE THREAD

**Issue by immrsui** [master-coder-ll/v2ray-web-manager#64]
试了好多次不成功，可否制作一键安装脚本？

**Comment by master-coder-ll** [comment]
欢迎RP

**Comment by immrsui** [comment]
我的意思我是小白，不会不懂啊 希望大神制作一个

**Comment by master-coder-ll** [comment]
> 我的意思我是小白，不会不懂啊 希望大神制作一个

自己动手丰衣足食。不然等其他有能力的人提交pull request

**Comment by greatbody** [comment]
> 我的意思我是小白，不会不懂啊 希望大神制作一个

可以看我最新的pull request，提供了通过docker启动的方法。

**Comment by dalaolala** [comment]
说实话已经很小白和简单了

**Comment by alun1** [comment]
> 说实话已经很小白和简单了

我也是，按照说明做，一直没成功，登录一直报502，log也没有打印。搞不懂哪里出错了

**Comment by ocdevcn** [comment]
> > 说实话已经很小白和简单了
> 
> 我也是，按照说明做，一直没成功，登录一直报502，log也没有打印。搞不懂哪里出错了

我装了一天登录都是： Request failed with status code 502 你解决了吗

**Comment by lilizi1125** [comment]
我也都是提示Request failed with status code 502
