### ISSUE TITLE
增加第二台v2ray服务vps不成功，请教

### ISSUE THREAD

**Issue by xueliqq** [master-coder-ll/v2ray-web-manager#67]
## 你的问题是什么？
我第一台装成功，但是第二台就不行
有问题先搜索Issues

## 出现问题的情况是怎么样的？
在第一台管理页面添加第二台服务器，使用v2ray二维码扫码成功但无法代理上网
重现步骤

## 我增设第二台的具体步骤如下：
1，按照第一台vps把必要的依赖命令包括v2ray装了；
2，下载nginx,配置80端口，服务器名暂为ip；
3，下载v2ray-proxy.yaml,修改权限密码和第一台vps一样
4，启动v2ray和java v2ray-proxy.jar proxy.yaml进程成功
5，到第一台vps管理端创建第二台服务器，端口80，域名为第二台vps的ip,

## 期望结果？
恳请大佬能够指点第二台如何增设？

**Comment by master-coder-ll** [comment]
https://github.com/master-coder-ll/v2ray-web-manager/blob/master/step-by-step-model.md
