### ISSUE TITLE
希望能建个TG群，希望能有渠道联系到作者！

### ISSUE THREAD

**Issue by houpi** [master-coder-ll/v2ray-web-manager#68]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

**Comment by master-coder-ll** [comment]
这里就可以联系到@_@

**Comment by houpi** [comment]
试了一次，WEB端倒是建起来了，用户也能建，在proxy查日志也都有反应，但是远端的v2ray貌似没有数据。应该是失败了。打算重新建在本地看看！

**Comment by houpi** [comment]
另外有个问题没想通，假设proxy端限制了用户的数率，而v2ray端却没有限制，在v2ray发送的数据比较多的情况下，proxy是缓存这个多出的数据？还是丢弃？缓存会不会造成内存过多？丢弃会不会造成带宽浪费？

**Comment by master-coder-ll** [comment]
> 另外有个问题没想通，假设proxy端限制了用户的数率，而v2ray端却没有限制，在v2ray发送的数据比较多的情况下，proxy是缓存这个多出的数据？还是丢弃？缓存会不会造成内存过多？丢弃会不会造成带宽浪费？

了解下TCP滑动窗口，你并没有了解项目
