### ISSUE TITLE
java启动问题

### ISSUE THREAD

**Issue by Jungle-Leesin** [master-coder-ll/v2ray-web-manager#69]

**Comment by master-coder-ll** [comment]
lsof -i:9091 
Kill 进程在起来

**Comment by Jungle-Leesin** [comment]
![1](https://user-images.githubusercontent.com/62128074/78027532-18fdea00-7390-11ea-8055-befbdcacf78d.png)
![2](https://user-images.githubusercontent.com/62128074/78027534-1a2f1700-7390-11ea-97bb-22fe19a526b4.png)
现在应该是启动成功了，但是网页还是没有反应，怎么解

**Comment by goodjimli** [comment]
你的ip暴露了，1.检查80 443端口是否打开 2.检查 nginx 起来没有 3. 检查 /opt/jar/web 目录下有数据。4。检查nignx 配置

**Comment by Jungle-Leesin** [comment]
没有哪里有ip啊，前面三个都没问题，nginx的配置只有红框的地方要改成自己的嘛，下面的127.0.0.1不用改吧？
![TIM截图20200401180700](https://user-images.githubusercontent.com/62128074/78125488-ac442780-7443-11ea-888c-d6dde90bdde6.png)

**Comment by master-coder-ll** [comment]
你的ip暴露了，1.检查80 443端口是否打开 2.检查 nginx 起来没有 3. 检查 /opt/jar/web 目录下有数据。4。检查nignx 配置

**Comment by Jungle-Leesin** [comment]
我检查了啊，都没什么问题

**Comment by Jungle-Leesin** [comment]
我看到ip了，不要紧，测试用的主机

**Comment by master-coder-ll** [comment]
> 我检查了啊，都没什么问题
一步步排除，再不行 建议你重新按照教程安装

**Comment by Jungle-Leesin** [comment]
不好意思的说，我做了三遍了，快哭了

**Comment by master-coder-ll** [comment]
> 不好意思的说，我做了三遍了，快哭了

这么多人都能部署起来~~，说明是项目教程都没问题。要不然一堆人反应了

**Comment by Jungle-Leesin** [comment]
要不我给你用户密码，你上去帮我看一下，老哥？我头都大

**Comment by master-coder-ll** [comment]
> 看一下

不搞这些

**Comment by Jungle-Leesin** [comment]
> > 看一下
> 
> 不搞这些

行吧，我再弄弄

**Comment by Jungle-Leesin** [comment]
我想问一下，这里填什么，不是太清楚
![TIM截图20200401193414](https://user-images.githubusercontent.com/62128074/78132724-d6034b80-744f-11ea-96c5-5202e603ca71.png)

**Comment by master-coder-ll** [comment]
我觉得你的问题在于：1. 学习使用搜索引擎。2. 学习 Linux 入门

学好了再来搞

**Comment by master-coder-ll** [comment]
> 我觉得你的问题在于：1. 学习使用搜索引擎。2. 学习 Linux 入门
> 
> 学好了再来搞

话有点难听，理是真
