### ISSUE TITLE
TLS加密问题

### ISSUE THREAD

**Issue by houpi** [master-coder-ll/v2ray-web-manager#70]
## 你的问题是什么？

假设proxy端设置了tls，那proxy端在与v2ray端通信时数据包是否也经过了tls加密？

## 出现问题的情况是怎么样的？

担心v2ray通信不安全被墙封

**Comment by master-coder-ll** [comment]
部署结构是怎么样的

**Comment by houpi** [comment]
v2ray Client在国内
一个proxy端在国内
多个v2ray Server在国外

我希望从Client -> proxy -> Server 间的数据均通过TLS加密

**Comment by master-coder-ll** [comment]
这是有可能的。
但是相对于多个client 分布在全国各地，访问 国外 proxy 安全一些。
proxy不支持tls加密。就是说 proxy -> Server 不能保证中间没有被中间人攻击，建议不要使用none的加密方式。
ws协议是一个很通用的传输协议。风险较低。

**Comment by master-coder-ll** [comment]
> 国外

当然，实现是基于VMess的。也不需要过分担心。
