### ISSUE TITLE
请教项目存放的位置

### ISSUE THREAD

**Issue by CaoLeiKe** [master-coder-ll/v2ray-web-manager#74]
你好。看到项目jar包从now服务器下载的。
想问一下now如何存放jar包呢。
希望大佬给予我一些帮助。
谢谢

**Comment by master-coder-ll** [comment]
一个脚本，根据GitHub api 获取项目最新的 release包

**Comment by CaoLeiKe** [comment]
大佬可以贴出来或者私发给我吗？
万分感谢

**Comment by master-coder-ll** [comment]
> 大佬可以贴出来或者私发给我吗？
> 万分感谢

并不是我写的，google。其实就是对 GitHub api 接口的封装。

**Comment by master-coder-ll** [comment]
一种叫 Serverless Functions 的玩意，像是门面或者装饰者模式

**Comment by CaoLeiKe** [comment]
好的。万分感谢。小弟在请教一个问题。就是目前我知道now.zh只能存放静态文件。你说的脚本now.zh可以在服务器上运行吗

**Comment by master-coder-ll** [comment]
> 好的。万分感谢。小弟在请教一个问题。就是目前我知道now.zh只能存放静态文件。你说的脚本now.zh可以在服务器上运行吗

https://zeit.co/docs/v2/serverless-functions/supported-languages

**Comment by CaoLeiKe** [comment]
感谢大佬🙌
