### ISSUE TITLE
404 无法登录 后端日志显示找不到/api/user/login

### ISSUE THREAD

**Issue by chengziorange** [master-coder-ll/v2ray-web-manager#75]
## 你的问题是什么？

admin和proxy都运行之后，网页上登录提示 `Request failed with status code 404` 

## 出现问题的情况是怎么样的？

按照教程的推荐配置，两个jar移到别处了，/opt/jar/db文件夹建好了并给了相应权限

## 相关日志 java服务日志位于/opt/jar/logs

![image](https://user-images.githubusercontent.com/30137964/78488514-5bea0400-777a-11ea-9225-4bd7508be613.png)

## 期望结果？
正常登录

**Comment by master-coder-ll** [comment]
nginx 配置错误
