### ISSUE TITLE
v1.1.1 isn't measuring bandwidth

### ISSUE THREAD

**Issue by Juancollado2003** [master-coder-ll/v2ray-web-manager#76]
Hi, on last version v1.1.1, bandwidth usage isn't being measuring, any clue please?

**Comment by master-coder-ll** [comment]
> Hi, on last version v1.1.1, bandwidth usage isn't being measuring, any clue please?

The latest version is v3.1.4.

Have logs or pi or pictures?

**Comment by Juancollado2003** [comment]
> > Hi, on last version v1.1.1, bandwidth usage isn't being measuring, any clue please?
> 
> The latest version is v3.1.4. I think you should upgrade .
> 
> Have logs or pictures?

After upgrade I will post the log if the bug continues, thanks for reply

**Comment by Juancollado2003** [comment]
> > Hi, on last version v1.1.1, bandwidth usage isn't being measuring, any clue please?
> 
> The latest version is v3.1.4. I think you should upgrade .
> 
> Have logs or pictures?

After upgrade, same behavior, please tell me what logs do you need?

**Comment by master-coder-ll** [comment]
Please upload screenshots， but I think your problem is caused by other versions of v2ray

**Comment by Juancollado2003** [comment]
> Please upload screenshots， but I think your problem is caused by other versions of v2ray

V2Ray logs shows io: read/write error

![IMG-20200406-WA0003](https://user-images.githubusercontent.com/51458491/78561357-93da6100-77e5-11ea-8da6-fe359d3d1bfd.jpg)
![IMG-20200406-WA0002](https://user-images.githubusercontent.com/51458491/78561361-95a42480-77e5-11ea-8779-73a19f0839fd.jpg)
![IMG-20200406-WA0001](https://user-images.githubusercontent.com/51458491/78561362-963cbb00-77e5-11ea-952d-cd3f798c556c.jpg)
![IMG-20200406-WA0000](https://user-images.githubusercontent.com/51458491/78561363-96d55180-77e5-11ea-94ef-33b51ad4529d.jpg)
![IMG-20200406-WA0004](https://user-images.githubusercontent.com/51458491/78561367-976de800-77e5-11ea-95b9-3030e64633c4.jpg)

**Comment by master-coder-ll** [comment]
What does the proxy output?

**Comment by Juancollado2003** [comment]
> What does the proxy output?
> 
> Bandwidth usage is calculated by proxy.
IPCENSURED is my ip server, I edited the log


![Screenshot_20200406-200936_MiXplorer](https://user-images.githubusercontent.com/51458491/78616575-93bc7e80-7842-11ea-94ad-3a4685fc4609.jpg)

**Comment by master-coder-ll** [comment]
?
The server traffic does not support statistics, but the account traffic can be counted, and the account traffic needs to be greater than 10MB to display.

**Comment by Juancollado2003** [comment]
> ?
> The server traffic does not support statistics, but the account traffic can be counted, and the account traffic needs to be greater than 10MB to display.

I have few days using the account, many gigabytes consumed, it shows 0mb counted, those logs looks normal to you?

**Comment by Juancollado2003** [comment]
I can see proxy is only listening on ipv6

**Comment by master-coder-ll** [comment]
> I can see proxy is only listening on ipv6

The interesting thing is that you can connect to the proxy, and the proxy can pull the account. 
Have you upgraded your admin? Upload some admin logs.

Use the `grep -A  'ERROR' logfile` command to get some error logs and upload

**Comment by Juancollado2003** [comment]
> > I can see proxy is only listening on ipv6
> 
> The interesting thing is that you can connect to the proxy, and the proxy can pull the account.
> Have you upgraded your admin? Upload some admin logs.
> 
> Use the `grep -A 'ERROR' logfile`
![20200407_090217](https://user-images.githubusercontent.com/51458491/78672352-85a44780-78ae-11ea-9ffc-f21c79924f79.jpg)
 command to get some error logs and upload

![Screenshot_20200407-090014_MiXplorer](https://user-images.githubusercontent.com/51458491/78672138-3e1dbb80-78ae-11ea-8a41-4b84e543499a.jpg)
![Screenshot_20200407-090000_MiXplorer](https://user-images.githubusercontent.com/51458491/78672145-3fe77f00-78ae-11ea-8b52-ee2a7880e1e1.jpg)

**Comment by master-coder-ll** [comment]
All logs look  normal. 
check `服务器列表-服务器-流量倍数` >0

**Comment by Juancollado2003** [comment]
> All logs look normal.
> check `服务器列表-服务器-流量倍数` >0

You mean grep -A `服务器列表-服务器-流量倍数` >0

**Comment by Juancollado2003** [comment]
> All logs look normal.
> Check `服务器列表-服务器-流量倍数` >0
> Maybe you should watch a video

Mostly traffic is streaming from YouTube and others streaming websites

**Comment by master-coder-ll** [comment]
upload  `账号管理、修改服务器`  screenshots

**Comment by Juancollado2003** [comment]
> upload `账号管理、修改服务器` screenshots

Sorry, I was confuse by translation, here they are, when you're ready to translate this panel just send me the lines and I will help you
![IMG-20200407-WA0003](https://user-images.githubusercontent.com/51458491/78712247-4f82ba00-78e6-11ea-8761-5e4db7c9cf22.jpg)
![IMG-20200407-WA0002](https://user-images.githubusercontent.com/51458491/78712252-50b3e700-78e6-11ea-9073-92b76c92c9c9.jpg)

**Comment by Juancollado2003** [comment]
Perhaps this means something to you 



![IMG-20200407-WA0007](https://user-images.githubusercontent.com/51458491/78729633-8cf83f00-7908-11ea-9bff-b99f1262a81f.jpg)
![IMG-20200407-WA0005](https://user-images.githubusercontent.com/51458491/78729658-98e40100-7908-11ea-922d-54382483f96b.jpg)

**Comment by master-coder-ll** [comment]
If you do not have multiple admins, it ’s still unclear what your problem is. It can only be handled as a case, waiting for more users to report same issues

**Comment by Juancollado2003** [comment]
> If you do not have multiple admins, it ’s still unclear what your problem is. It can only be handled as a single case, waiting for more users to report same issues

I have 2 admin account, the second one I created thinking the problem was on the first account, here is another log
![Screenshot_20200408-064958_MiXplorer](https://user-images.githubusercontent.com/51458491/78776027-34a35a80-7965-11ea-9b98-9042e21e4fb2.jpg)

**Comment by master-coder-ll** [comment]
Your problem is using multiple admins, please turn off one of them and all proxies point to the unique admin

**Comment by Juancollado2003** [comment]
> Your problem is using multiple admins, please turn off one of them and all proxies point to the unique admin

Let's try that

**Comment by Juancollado2003** [comment]
. 

> > Your problem is using multiple admins, please turn off one of them and all proxies point to the unique admin
> 
> Let's try that

Already tried, same behavior, I will keep digging

**Comment by Juancollado2003** [comment]
Now with only one admin account all entries are from localhost 
![Screenshot_20200409-180145_Termius](https://user-images.githubusercontent.com/51458491/78944600-46335200-7a8c-11ea-91c9-c5a2ed3983bb.jpg)

**Comment by master-coder-ll** [comment]
Not an admin account, but an admin service.
