### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by Juancollado2003** [master-coder-ll/v2ray-web-manager#8]
Hi, is there any chance to get this project translated? Is there any chat group for this? Thanks

**Comment by Juancollado2003** [comment]
I can help

**Comment by master-coder-ll** [comment]
thx

**Comment by doutuo** [comment]
> 谢谢

兄弟，谢谢了，刚下了你的面板和管理系统，在用了，功能挺好的，提个建议，注册用户可否不一定要用邮箱注册呢？其它的用户名是否可以？
