### ISSUE TITLE
连接数设定原则是？速率设定后，通过什么标准测试方案，才能验证这个设定呢？

### ISSUE THREAD

**Issue by matthuo333** [master-coder-ll/v2ray-web-manager#81]
## 你的问题是什么？

有问题先搜索Issues

已搜。没有对应的。

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
明确清楚设定原则。以及方案步骤

**Comment by master-coder-ll** [comment]
连接数设定原则： 开启多路复用情况下，16连接数足够。不开启64左右吧。

测速：全局模式下跑speedTest
