### ISSUE TITLE
centos 7.6 使用开机脚本提示：failed because the control process exited with error code. See "systemctl status v2panel.service" and "journalctl -xe" for details.

### ISSUE THREAD

**Issue by jelly0925** [master-coder-ll/v2ray-web-manager#83]
有大佬帮看看？谢谢
[root@docker ~]#  systemctl start v2panel
Job for v2panel.service failed because the control process exited with error code. See "systemctl status v2panel.service" and "journalctl -xe" for details.

**Comment by master-coder-ll** [comment]
--> See "systemctl status v2panel.service" and "journalctl -xe" for details.
