### ISSUE TITLE
issue: upstream prematurely closed connection

### ISSUE THREAD

**Issue by matthuo333** [master-coder-ll/v2ray-web-manager#86]
## 你的问题是什么？
nginx error log:
020/04/15 15:17:42 [error] 16319#16319: *129 upstream prematurely closed connection while reading response header from upstream, client: x.x.x.1, server: x.x.x.2, request: "GET /ws/admin-matt:xxxxxxxxxxxxx/ HTTP/1.1", upstream: "http://127.0.0.1:xxxx/ws/admin-matt:xxxxxxxxxxxxx/", host: "x.x.x.2

不能正常访问外网。当时报错见上

有问题先搜索Issues

## 出现问题的情况是怎么样的？
1.之前正常
2.修改本地的透明代理后，发现不能访问。
3.查nginx 日志
4.调大admin连接数后，正常

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
这个错误是连接数小导致（实际当时连接数是32）？ 还是什么别的原因所致？根本解决方案是？

**Comment by master-coder-ll** [comment]
#13
