### ISSUE TITLE
建议使用CI/CD工具进行打包和发布。

### ISSUE THREAD

**Issue by greatbody** [master-coder-ll/v2ray-web-manager#87]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？

提交的代码，可以通过CI/CD工具打包，做到自动化更新，自动化更新docker.io上的镜像。

**Comment by master-coder-ll** [comment]
好吧，等有时间在搞搞，可以尝试结合现在的CI工具。

实用性不高，优先级**低**
