### ISSUE TITLE
新添加账号的“结算时间”无法灵活控制

### ISSUE THREAD

**Issue by xifanu** [master-coder-ll/v2ray-web-manager#88]
## 你的问题是什么？
新添加的账号结算时间无法灵活控制.

## 出现问题的情况是怎么样的？

添加账号后，默认的“**周期**”为1，“**结算时间**”的默认值为注册时间的后一天，导致一天后必定重置流量数据；

## 处理方案？

- [ ] 修改前台，灵活定义结算时间，后台代码增加校验；

- [ ] 仅修改后台，根据账号**有效时间**与**周期**，推演出下一次的结算时间；

- [ ] 其他处理方案？

**Comment by master-coder-ll** [comment]
现在就是根据账号有效时间与周期，推演出下一次的结算时间，大概算法

结算时间=min（上次结算时间()+周期,有效时间）。

**Comment by master-coder-ll** [comment]
就像你说的，如果可以灵活定义结算时间，后台需要增加校验，同时会**破坏**现有的 计算规则。
挺纠结的。所有我偏向于2

**Comment by master-coder-ll** [comment]
这样来吧，新用户调整默认的结算周期为`30天`，但是账号的`有效时间`还是为1天
