### ISSUE TITLE
Config json

### ISSUE THREAD

**Issue by Juancollado2003** [master-coder-ll/v2ray-web-manager#9]
Hi, in my case the panel is not modifying the config json file, any v2ray server I make is not working, any help please?

**Comment by Siris-Rose** [comment]
> Hi, in my case the panel is not modifying the config json file, any v2ray server I make is not working, any help please?

Same problem... How did you solve it?

**Comment by Juancollado2003** [comment]
> > Hi, in my case the panel is not modifying the config json file, any v2ray server I make is not working, any help please?
> 
> Same problem... How did you solve it?

Panel doesn't touch config json, all config pass through the Java proxy, which means all clients use the same setup config json
