### ISSUE TITLE
admin面板中对于“周期”设置不生效

### ISSUE THREAD

**Issue by matthuo333** [master-coder-ll/v2ray-web-manager#91]
## 你的问题是什么？
如题。理解“周期”是在设定的天数到达后，自动清零。但实际看来并未生效。
有问题先搜索Issues

## 出现问题的情况是怎么样的？
设置了1，即为一天，可是第二天流量并未清零
重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
期望流量显示和实际均清零，如你的设计预期

**Comment by master-coder-ll** [comment]
周期默认是一个月，修改周期后，需要下一个周期才会生效

**Comment by matthuo333** [comment]
> 周期默认是一个月，修改周期后，需要下一个周期才会生效

但是单位不是天么？意思改成1天，也要等待到一个月后生效成1天？

**Comment by master-coder-ll** [comment]
> > 周期默认是一个月，修改周期后，需要下一个周期才会生效
> 
> 但是单位不是天么？意思改成1天，也要等待到一个月后生效成1天？

查看账号结算时间，以结算时间时间为准，旧的结算时间过后，会使用新的周期计算下一次的的计算时间。

**Comment by matt19891231** [comment]
你好，貌似限速其他用户的限速不起作用，请问怎么解决

**Comment by matthuo333** [comment]
> > > 周期默认是一个月，修改周期后，需要下一个周期才会生效
> 
> > 
> 
> > 但是单位不是天么？意思改成1天，也要等待到一个月后生效成1天？
> 
> 
> 
> 查看账号结算时间，以结算时间时间为准，旧的结算时间过后，会使用新的周期计算下一次的的结算时间。

貌似结算时间没法直接设置
