### ISSUE TITLE
centos 7 安装BBR加速之后，admin管理面板登录提示Network Error

### ISSUE THREAD

**Issue by jnsday** [master-coder-ll/v2ray-web-manager#93]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

在个空白的centos 7的VPS上部署完成之后，用下面的脚本开启BBR
wget -O- http://soft.wellphp.com/scripts/install_bbr_centos.sh | bash
之后面板与proxy就无法正常使用了

## 相关日志 java服务日志位于/opt/jar/logs

相关输出

## 期望结果？
期望可以开启BBR或者 锐速 加速

**Comment by jnsday** [comment]
重做了VPS系统，先装了锐速，正常了

**Comment by master-coder-ll** [comment]
猜想：I/O 操作都基于底层的 `文件描述符fd`，所有更换TCP算法，导致TCP底层的变化，导致Java监听的`文件描述符` 失效。
猜想解决方法: **重启Java服务**
