### ISSUE TITLE
关于docker

### ISSUE THREAD

**Issue by ghost** [master-coder-ll/v2ray-web-manager#95]
教程说docker还不支持nginx-tls，我觉得在v2ray-mng.conf中配置tls参数和监听443，然后把证书挂载进docker就可以了。你觉得呢？

**Comment by newsouther** [comment]
另外，我是docker忠实粉丝，希望下个版本可以做到nginx、前后端分开，遵循一个容器一个服务原则（因为我服务器已经有了nginx、redis、mysql容器）。

**Comment by master-coder-ll** [comment]
我想法也是这样，现状是廉价的VPS跑不太合适，并且情况也复杂。

**Comment by greatbody** [comment]
> 另外，我是docker忠实粉丝，希望下个版本可以做到nginx、前后端分开，遵循一个容器一个服务原则（因为我服务器已经有了nginx、redis、mysql容器）。

我当年写的时候偷懒了
