### ISSUE TITLE
大神，关于admin和proxy这两个怎么升级？

### ISSUE THREAD

**Issue by doutuo** [master-coder-ll/v2ray-web-manager#97]
大神，我用的咱们源码时间久了些，现在要升级到新版，我怎么查看我老的版本号？
升级最新版是直接下载admin和proxy 这两个Jar解压覆盖吗？

**Comment by master-coder-ll** [comment]
建议备份 jar 文件和 db 目录， 在重新下载 jar 包更新

**Comment by GeorgeChen0821** [comment]
> 建议备份 jar 文件和 db 目录， 在重新下载 jar 包更新

更新完以后 新用户注册 没办法收到验证码了 之前都正常

**Comment by GeorgeChen0821** [comment]
> 大神，我用的咱们源码时间久了些，现在要升级到新版，我怎么查看我老的版本号？
> 升级最新版是直接下载admin和proxy 这两个Jar解压覆盖吗？

老哥 怎么样 更新了吗？有啥问题不
